---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pocket-id-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hcloud-volumes
  csi:
    driver: csi.hetzner.cloud
    volumeHandle: "105555376"
    fsType: ext4
  claimRef:
    namespace: identity
    name: pocket-id-data
