apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:OSEIej/vwKHwM3A9jSStY+uvCsOT8pJxYC2CqAzDyCgoiXlGdDWIK8nKKpg=,iv:I6BR2brkGdNN/sCXEJp7idDuPFVmB2syX+TWFfcl7Qg=,tag:iFAqzOF64x/w8yRIhzQToA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:Q2Q/prbqU4M54urgSwF9RBIwQgii+Dcb2o9jx+YkyxRiuJWLmRRe7FiBlQBLd9upbCwJHTYve9/TjSbn8gYCUTohkVHvmMoaLlpZhzCfiiR50b2ae4TUmQ==,iv:kZD9quqhbf8G2G9JhvD9wZMd8/l1SlqPdAow4OUeTgw=,tag:l0ojwnkZU/ndx/ZANvKRdQ==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: identity
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK1Z1eFRjbWNxRVhIZnNj
            elRRZGVNT21CR3ZBRTJ1ZEY3RXA0akxURXhRCkFybVVSSWsydno1VTR0b1lMdlJ0
            R2t0TWlOdGZHemQ3K0RwZS92d1U4c3MKLS0tIFhxbUd1by9RS2ZtKzdhR1RZL29l
            cGt4bk4wU3dJVW51VENTb3kzOC8rMWcKXG22StESEke6Wf19mo8Tbc9Nt63MPQRi
            v13XQ/iM2WAjMOmeC248OwltXjgkr6cfg2eDKjoRzzwusVkK1dJG4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T12:26:18Z"
    mac: ENC[AES256_GCM,data:vSxEvf+oG9pSblX74MzWrum0vEbDibB95US4l7bTLTBU6r+ShL3cPhuS0oVko28VRan8Hd6VYW7qxHljLa7EGwU69loFM740U+QSU8LUpnGt1RAFNlN13dhzSTpMQWl9VAhKLgCU39gPGrDnp0w4M/RsihNkA05z7nSCn+uwXEE=,iv:2HrM8q1VBkcQdqYJGtbBxEd0SWgFLjYtEfhH3EZTGhM=,tag:8rr7ja69Idt9OtKEeZ981g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
