---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=72.0.0 <73.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheusOperator:
      resources:
        requests:
          cpu: 1m
          memory: 32Mi
        limits:
          memory: 128Mi
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 1m
            memory: 256Mi
          limits:
            memory: 512Mi
        enableRemoteWriteReceiver: true
    grafana:
      admin:
        existingSecret: grafana-admin
        userKey: admin-user
        passwordKey: admin-password
      resources:
        requests:
          cpu: 1m
          memory: 128Mi
        limits:
          memory: 256Mi
    alertmanager:
      enabled: false
    nodeExporter:
      resources:
        requests:
          cpu: 1m
          memory: 32Mi
        limits:
          memory: 64Mi
    kube-state-metrics:
      resources:
        requests:
          cpu: 1m
          memory: 32Mi
        limits:
          memory: 64Mi
