apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:0RuVaFIfQ4yDPSniRvvwrZDZcU4fNFPeZVCVU5K3ZuQGTTOQZAFIAFZ9+Ybrb9i+EjNOXX/3x36ZSKtowj+Dpnb2dOBAYilAI64WQ/WuZKnfb9JzatCkAfO8G0D9O6rhl95lYDvHT5mGfd7hbyccp3aLZ5HMnyJe4j9zCa+xljrVyQ+1WSCcdBDUaMNwZQNsGzgvpkxIZL8=,iv:8SFNV4/9AJPLu5QDTiYYK/EMSabCbTo29WkAEFXsQcg=,tag:ABKI4wBECz1mqqbiQCvnUw==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOGVaUjNjek9UUmVXN3Y0
            ZjRMblZJa2UwU3hoT2JhVzFuNlFZRjBHMFV3Clp3U0ZySFBUcTNmd0VYMHZuQlRC
            eWNublYyU09YNDRkejBTMmQ2bld1U3cKLS0tIFdMenF0dmRWekluM0xvM0hpUEdU
            YlV6VktUZUIwbHQ1ZzFiMnErT0l1VWMKnSC/zRyxwyvH6wIEJGjctNenYg00pgKN
            Wd63xBGanf812O3aznoHw6lXygo2qHhHTHaGvH4+rBS1xMMImneQTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T19:10:27Z"
    mac: ENC[AES256_GCM,data:unSbQSj+n7AC+kLTv5M7fddwvSGJXnLoNNeKdAsOdiIKIzPPX5uVpjlpbCiIu8NtCWRBkVq8ENldgv1xS5vItZG4I4l2ip5Lg2WQovJUYnwI4A2F3rGQz89cXal92CjbMfiL5DUvYIqX641NNYqELSutOjPUYUemv4ZMfT7o6c8=,iv:EcaQnuckiWFUmE3KgYjHEK5iYMF4bNgBNpW1k16IhsY=,tag:Jts221KhbHLITOOmuLuFeQ==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
