apiVersion: v1
kind: ConfigMap
metadata:
  name: cf-tunnel-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: sleepy-notify
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: wg-admin.la.fish
        service: http://wg-easy-http.vpn.svc.cluster.local:51821
        httpHostHeader: wg-easy-http.vpn.svc.cluster.local
      - hostname: booklore.la.fish
        service: http://booklore.booklore.svc.cluster.local:6060
        httpHostHeader: booklore.booklore.svc.cluster.local
      - hostname: grafana.la.fish
        service: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
        httpHostHeader: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
      - hostname: prometheus.la.fish
        service: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        httpHostHeader: kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
      - service: http_status:404