---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: files
data:
  config.yaml: |
    server:
      port: 80
      baseURL: "/"
      sources:
        - path: /srv/books
          name: books
    auth:
      methods:
        password:
          enabled: false
        oidc:
          enabled: true
          issuerUrl: "https://${HOSTNAME_AUTH}"
          scopes: "openid email profile groups"
          userIdentifier: "preferred_username"
          adminGroup: "admin"
          groupsClaim: "groups"
