apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-oidc
    namespace: files
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:Dt5wFxeNKHbmTZLdTWF0tdkx/8fjM3CEBeERCsinzXQcVt9d,iv:UhguJLptlzcS8xyKhiXdaF2y2CktbLFZTDChRprUqIg=,tag:aAz4etlkUscMGr25UT503A==,type:str]
    clientSecret: ENC[AES256_GCM,data:BxT636/q7p8YSEsCGDK4vA9c6A/R78xqLqQbgoZWPOU=,iv:5JK9VGlzKsR/btdxdIW2SXu7QND8gEULJTrL8gHdQe4=,tag:xP+mkSECoAEteAD3u0dDyA==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR01SU1VsY1lHR1FYT080
            MUtRTS83d2xNN3hKZU9vM0lwZDFGZ3lCdVI0CkJhMzk4OVZHUGsvS1MvVU1JWm5h
            VmlPSE90QlV4d2VNL0JScGtJcWJvZkkKLS0tIDlYSVhqNlZMcDU0Y3JQL2pKcmc2
            N1VUTFBFaWc3U3hBK25VRmgzeEJwZXcKN8OUQVff28jYxQqMXPGonzT+IDM4gWIw
            bCPvm7nKEtb4llFUGhQ0xPAo2qyIWGxayFqngVzAdQSLLrJpa/fUKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T19:48:31Z"
    mac: ENC[AES256_GCM,data:fJ/PF2qFUeigQZkfkbnqTE6qp4twAkl89758t2+DYpsgzC26Z9iKsEgHK9yiJuOneDcZ7c4XixdZBAnh22yqL/aH5QswCh6wkSI9mH8ANpnLGKPIDKl3J2/WX3TMXUzdWYr/03f5iE5m79mSx0LAFIG3mesW41K5blrBeVVufSA=,iv:wEQwIfbIYGb/xsptwb1/UXudtsWdA2KVPccXZy8kNy0=,tag:7PaCrPZrruZq5DGawXyr5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
