---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-books-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: books-nfs-bridge
    volumeAttributes:
      server: books-nfs.booklore.svc.cluster.local
      share: /
  mountOptions:
    - nfsvers=3
    - nolock
    - port=2049
    - mountport=2049
    - noresvport
    - tcp
  claimRef:
    namespace: files
    name: master-books
