---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vrising-cm
  namespace: vrising
data:
  TZ: "UTC"
  SERVERNAME: "Fabler"
  WORLDNAME: "circassia"
  GAMEPORT: "9876"
  QUERYPORT: "9877"
  LOGDAYS: "7"
  HOST_SETTINGS_LowerFPSWhenEmpty: "true"
  HOST_SETTINGS_LowerFPSWhenEmptyValue: "10"
  HOST_SETTINGS_Secure: "true"
  HOST_SETTINGS_ListOnSteam: "false"
  HOST_SETTINGS_ListOnEOS: "false"
  HOST_SETTINGS_HideIPAddress: "true"
  HOST_SETTINGS_GameSettingsPreset: "StandardPvE"
  HOST_SETTINGS_GameDifficultyPreset: "Difficulty_Normal"
  HOST_SETTINGS_MaxConnectedUsers: "10"
  HOST_SETTINGS_MaxConnectedAdmins: "4"
  HOST_SETTINGS_AutoSaveCount: "40"
  HOST_SETTINGS_AutoSaveInterval: "120"
  GAME_SETTINGS_GameModeType: "0"
  GAME_SETTINGS_DeathContainerPermission: "1"
  GAME_SETTINGS_RelicSpawnType: "1"
  GAME_SETTINGS_BloodBoundEquipment: "true"
  GAME_SETTINGS_TeleportBoundItems: "false"
  GAME_SETTINGS_BatBoundItems: "false"
  GAME_SETTINGS_BatBoundShards: "false"
  GAME_SETTINGS_CastleRelocationEnabled: "true"
  GAME_SETTINGS_InventoryStacksModifier: "3.0"
  GAME_SETTINGS_DropTableModifier_General: "2.0"
  GAME_SETTINGS_DropTableModifier_Missions: "2.0"
  GAME_SETTINGS_DropTableModifier_StygianShards: "2.0"
  GAME_SETTINGS_SoulShard_DurabilityLossRate: "0.25"
  GAME_SETTINGS_MaterialYieldModifier_Global: "2.0"
  GAME_SETTINGS_BloodEssenceYieldModifier: "2.0"
  GAME_SETTINGS_DurabilityDrainModifier: "0.5"
  GAME_SETTINGS_ServantConvertRateModifier: "2.0"
  GAME_SETTINGS_CanLootEnemyContainers: "false"
  GAME_SETTINGS_CastleHeartDamageMode: "0"
  GAME_SETTINGS_Death_DurabilityFactorLoss: "0.0"
  GAME_SETTINGS_Death_DurabilityLossFactorAsResources: "0.0"
  GAME_SETTINGS_AnnounceSiegeWeaponSpawn: "false"
