---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vrising-cm
  namespace: vrising
data:
  TZ: "UTC"
  SERVERNAME: "Fabler"
  WORLDNAME: "circassia"
  GAMEPORT: "9876"
  QUERYPORT: "9877"
  LOGDAYS: "7"
  HOST_SETTINGS_Secure: "true"
  HOST_SETTINGS_ListOnSteam: "true"
  HOST_SETTINGS_ListOnEOS: "true"
  HOST_SETTINGS_GameSettingsPreset: ""
  HOST_SETTINGS_GameDifficultyPreset: ""
  HOST_SETTINGS_MaxConnectedUsers: "10"
  HOST_SETTINGS_MaxConnectedAdmins: "4"
  HOST_SETTINGS_AutoSaveCount: "40"
  HOST_SETTINGS_AutoSaveInterval: "120"
  GAME_SETTINGS_GameModeType: "PvE"
  GAME_SETTINGS_DeathContainerPermission: "ClanMembers"
  GAME_SETTINGS_RelicSpawnType: "Plentiful"
  GAME_SETTINGS_BloodBoundEquipment: "true"
  GAME_SETTINGS_TeleportBoundItems: "false"
  GAME_SETTINGS_BatBoundItems: "false"
  GAME_SETTINGS_BatBoundShards: "false"
  GAME_SETTINGS_CastleRelocationEnabled: "true"
  GAME_SETTINGS_InventoryStacksModifier: "3.0"
  GAME_SETTINGS_DropTableModifier_General: "3.0"
  GAME_SETTINGS_DropTableModifier_Missions: "3.0"
  GAME_SETTINGS_DropTableModifier_StygianShards: "3.0"
  GAME_SETTINGS_SoulShard_DurabilityLossRate: "0.25"
  GAME_SETTINGS_MaterialYieldModifier_Global: "3.0"
  GAME_SETTINGS_BloodEssenceYieldModifier: "3.0"
  GAME_SETTINGS_DurabilityDrainModifier: "0.0"
  GAME_SETTINGS_ServantConvertRateModifier: "2.0"
  GAME_SETTINGS_SunDamageModifier: "0.5"
  GAME_SETTINGS_CastleBloodEssenceDrainModifier: "0.5"
  GAME_SETTINGS_BuildCostModifier: "0.5"
  GAME_SETTINGS_RecipeCostModifier: "0.5"
  GAME_SETTINGS_CraftRateModifier: "1.0"
  GAME_SETTINGS_RefinementCostModifier: "0.5"
  GAME_SETTINGS_RepairCostModifier: "0.5"
  GAME_SETTINGS_CanLootEnemyContainers: "false"
  GAME_SETTINGS_CastleHeartDamageMode: "CanBeDestroyedOnlyWhenDecaying"
  GAME_SETTINGS_Death_DurabilityFactorLoss: "0.0"
  GAME_SETTINGS_Death_DurabilityLossFactorAsResources: "0.0"
  GAME_SETTINGS_AnnounceSiegeWeaponSpawn: "false"
  GAME_SETTINGS_CastleStatModifiers_Global__CastleLimit: "5"
  GAME_SETTINGS_CastleStatModifiers_Global__HeartLimits__Level4__ServantLimit: "9"
  GAME_SETTINGS_CastleStatModifiers_Global__HeartLimits__Level5__ServantLimit: "12"
  GAME_SETTINGS_CastleStatModifiers_Global__HeartLimits__Level4__HeightLimit: "4"
  GAME_SETTINGS_CastleStatModifiers_Global__HeartLimits__Level5__HeightLimit: "6"
  GAME_SETTINGS_CastleStatModifiers_Global__HeartLimits__Level4__FloorLimit: "400"
  GAME_SETTINGS_CastleStatModifiers_Global__HeartLimits__Level5__FloorLimit: "650"
