apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4Y8yoX3VWTOcHyandJ8ECD1p4ETS27m56rnnEV8cv+PTcb7DAJH64217H1U0WQ6zkaLJKyuoTJK6p9KfY0DkDpqUvpMvxv8DcipTDVQ4RMN5bk7ik8gJ/+fILiyvD4R6XrmE1k5XLoPbJHq1By3TgPB/MQhAtOU+7iVn+ySXKw/ktPrd,iv:dWzihBa4/DO6pDne5VKcZusjCOEOL3p6m3f7Jv6GXLA=,tag:ThpuRiHgy8ALNCyqol/AHA==,type:str]
kind: Secret
metadata:
    name: wg-easy-password
    namespace: vpn
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N1h1ckpyUWk3UzZOZ2h5
            eWFsQzM2YWQxaU9sbGZLZ3l2SXoxOTVkUW5RCmx0TUdYUi9nNnE0R25nY0piTjRT
            WSt6UDR0aXd3ZXpGZko1cU9FU1U5VWcKLS0tIG1mL2RnV1hpbERZMFVTRzE5eW9t
            eW52UVFqNTFRQTE4WEtjWmxSSkQwVnMKVR5ep+1p4QA09fz08stFd+frX4cYtKP3
            5sRwxfFfBjFxiv2o8CZtzZqg0U7L5V9W3Z7YRSVA9LuT/jszL3ndyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T01:35:32Z"
    mac: ENC[AES256_GCM,data:/L27jMdFzT8SU5ZIbdFekwXccoOm5Rp8c6t7k6uDQqbg9lKXhOLbjjy6AoMKmJAL1QeIBPsF5fLNLb0vCZKc6zj8tWbgr8hv2aivht4A5sRsZBMo/2r8djZazfhUP/qE66c7gM1RBzyg/a/DIrZjBnRom9D8lOAHqlNBmaOHzHI=,iv:Eeb2ELMNGvGv4eKfGsmzQsjK/WW1BT7FBhYxvScotUo=,tag:arTcUJ2lDj4yEmKoOKAk/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
