---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: paperless
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    includedNamespaces: [paperless]
    storageLocation: r2
    ttl: 336h0m0s
    defaultVolumesToFsBackup: true
    hooks:
      resources:
        - name: paperless-export
          includedNamespaces: [paperless]
          labelSelector:
            matchLabels:
              app: paperless
          pre:
            - exec:
                container: paperless
                command:
                  - /bin/sh
                  - -c
                  - "cd /usr/src/paperless/src && python3 manage.py document_exporter -na -nt -f /usr/src/paperless/export"
                onError: Fail
                timeout: 20m
        - name: postgres-dump
          includedNamespaces: [paperless]
          labelSelector:
            matchLabels:
              app: postgres
          pre:
            - exec:
                container: postgres
                command:
                  - /bin/sh
                  - -c
                  - "pg_dump -U paperless paperless | gzip > /var/lib/postgresql/data/dump.sql.gz"
                onError: Fail
                timeout: 10m
          post:
            - exec:
                container: postgres
                command:
                  - /bin/sh
                  - -c
                  - "rm -f /var/lib/postgresql/data/dump.sql.gz"
                onError: Continue
                timeout: 1m
