---
apiVersion: v1
kind: Service
metadata:
  name: core-keeper
  namespace: core-keeper
  labels:
    app: core-keeper
spec:
  type: NodePort
  ports:
    - port: 30668
      targetPort: 30668
      protocol: UDP
      nodePort: 30668
  selector:
    app: core-keeper
