apiVersion: v1
data:
    network: ENC[AES256_GCM,data:XPqsGMkCj2hO88si,iv:HINHgGFrFyUb6x/AcEPlmoBVq72E9ZVG72wfrugD5Es=,tag:tPlqIaIPkQnmvD/aUC4qZw==,type:str]
    token: ENC[AES256_GCM,data:18NSOUlErp4jsqAZb+MCcwttLGYuhYxeJFKT77Goe2wG3NpFu0+zbCyUmqf7c9djztorBqrSYvh1EiJMgbv7ipI3YR+NHNF6lVcAf3Apf507fbK4PXMTLg==,iv:agi0l69hCDmG3pG9FX2zOZP8XwlbHySzyYs/xYA+cs4=,tag:MY0w1Ub5NZJy+2sCoPFnxg==,type:str]
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQjFVcHRYRHVBUU1hNXVv
            WXBiL2pNMUh1OC80Z21BYk9wVEVqY0V4WG1jCk5sNnJCaE43WnhWTUFRQXovYURL
            QXhVSCtZd0k4SmhyNXRveTZjZFhUWWsKLS0tIGZNNTBpZ1NDdFVCdFFFU3JSZ3p2
            VEdNSzZJNzRzNDB2blBOdEJGY3NSWVEKWOQmAnzsQM1Ed0LaZcxCaVovgb3bcvGJ
            EHBWZBDznkXchisvyNltl3+2SRCKX1Kl2ViOaNt1Faij8ZZHyCzFbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T01:35:32Z"
    mac: ENC[AES256_GCM,data:I1pMYmZKlIEx1poutZwwh2o3X6KcdVNOLIHAfbDac92DcqmjF8hxOsPw1aDut8l4IRowhdeq7znnp6NgKBhMR+xkjcSwtmFpUn+eqivDA+7wOqkMNWx1q/31qnSFcc5xeIQHgSIssrStyYIG6WSw2hYGt/ZyVWtaNIxbjTCGI5k=,iv:t3LG9olkE0zMhFTlvb6TMOcVW6blniDAUco7Cn6ZZCU=,tag:bwyoNbU+o2fTa8nOOyYsoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
