---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: booklore
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    includedNamespaces: [booklore]
    storageLocation: r2
    ttl: 720h0m0s
    defaultVolumesToFsBackup: true
    hooks:
      resources:
        - name: mariadb-dump
          includedNamespaces: [booklore]
          labelSelector:
            matchLabels:
              app: mariadb
          pre:
            - exec:
                container: mariadb
                command:
                  - /bin/sh
                  - -c
                  - 'mariadb-dump -u root -p"$MYSQL_ROOT_PASSWORD" --all-databases --single-transaction --routines --triggers | gzip > /var/lib/mysql/dump.sql.gz'
                onError: Fail
                timeout: 10m
          post:
            - exec:
                container: mariadb
                command:
                  - /bin/sh
                  - -c
                  - "rm -f /var/lib/mysql/dump.sql.gz"
                onError: Continue
                timeout: 1m
