apiVersion: v1
data:
    mysql-password: ENC[AES256_GCM,data:7GPFeCunra5MoUj4sMHDroUvlfQR3sFZwh1abQ==,iv:iZgdXl0TPBi3QB7VRg/i91uza676Popn/de+zQ6GBMU=,tag:6c/7EsHGj5dMHdt0VeZm+A==,type:str]
    mysql-root-password: ENC[AES256_GCM,data:LDVbr8Yu7hOKjlYVqbcfGL7x7T/7OXmg11g/OA==,iv:PPXt91r0CLvprvNEzuASG7hK2cCx+n4iXizUCmtWYtM=,tag:Xpb5JHj/7crv/v7e4CgrAg==,type:str]
kind: Secret
metadata:
    name: booklore-db
    namespace: booklore
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINlJDWTEvWVRIVmFMVlND
            WVc5YXdrUEN6Uys2VTAyZlFqZXE0NUt5UEQ4Cm9xTkVlMDkxczJWQlBudTlGOU83
            Q3k1eis4QUhJVTVkNXh5bFM1bnJQUGsKLS0tIFZIbEFpK0R3VWxjWjUrdTBrNmlq
            a0V4dm84d01XSEFldzJLak1zL1VKYjQK+7WIDJ+kQ3H7ADazrg4ygjuqS7Uh1SnL
            OvT31mMdZ7BiT7Y941dVTcK8y5aA6Vb7jr/iSGnoncG50l4k7/Gp7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T01:35:31Z"
    mac: ENC[AES256_GCM,data:JEihHz6gvAzC1ObwBuzJfs1C/ZuVkW5uM+zplW3t1GtZX8ZpLhFyY41NF7FY0o9Wccrow4mCJctDwKAGgEIzuJabd0fBR/X5N4V0EDPflswoYsScaibKOlBsGCIAcp473aCX/N+gguDjtATOsvfpS2/GnFS7/vZw2J+E4tGHj7E=,iv:i/X1MnYH03WqD9cpTgC70A0XGZNl0gCyxtDS1ww4A7I=,tag:3DExUXQDD7fxMQch40l4fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
