---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - telegram-ghcr-secret.yaml
  - telegram-sleepy-bot-secrets.yaml
  - booklore-booklore-db.yaml
  - cloudflared-cf-tunnel-secret.yaml
  - vpn-wg-easy-password.yaml
  - kube-system-hcloud.yaml
  - monitoring-grafana-admin.yaml
