apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Tb9Om91giy0XGWG+MoPZlI6MTqyQ4qg6Y83Ula6LTvHfzUhO1FEjhbaZvZ9rJSKuPYKwbdxD9e4gZtgg4mqqZWt9RiLvSCwahMRxeZfvfLQlMmZQRLokuA7OQlCyGHJtelA6nkFFJnaUPRaKcHO+SMu79Hc4A0wgllUil9q7jKBa3PZUVdwnbjBv/biVTd7XTyn/yUrkNUMkfuYc37ruQBpTADE+lxu3pUJKxXikb91nJlyj6+PqD7nMx4duzSFbbZUVGePtP4xjP8IBRhM/ATWbsz+mDLol78Eze+S9DMUDjMDfKymRdMwvMZjRCa5n,iv:ZzYbAVEWBKHTGdeNLnu4wpM5RqhtBcCEPMF6NkBUaCA=,tag:nPR1nddTCDS4urrbErQxnw==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: telegram
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKa29ndTBldjNBZjBCV0FN
            eXZZakhMelNrKzg3NXI1NjQ0dzI0MlRqR1VVCkFjRysvVUxlT1JJTkVnVCs1SThk
            V3RQRlN5YU1pR0NZdzhReFB4aG9UOVEKLS0tIDBPWFFHRlBXTGhjNnFvZXZoS2dz
            VmsrYWQ4cThRQjRJR2NnYnR2OFF1RjQKqmDLfqJMMDcWx3J6yxZfiWoQeP0ECV2C
            NOXHH2GARpM3h3TqkXG/7az6OhjIlQG3NvFoyXHYDtx8RhrmG0A/uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T01:35:31Z"
    mac: ENC[AES256_GCM,data:gDGDL2lrG9eS4JfERzAyeT7zdo6MUOl1344CsGomNKLRYmepcFKFkvsnxP0ige+RtV2S6AZhjY57OTvr99Cy7ICRd4jmBDJmKrI7DSTgz+Xl3SH8nIsUtrQm9a2t+099b3P5R8W671LZYirIZpuxTnXGjoxr1TumUyR0Ik7nEvE=,iv:PPz+Elo0ISH7v8KELu/uCFnKriF9xabkuP7Rd3LqB1g=,tag:U3QUZDxNbn/sevzzzD+1rA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
