apiVersion: v1
data:
    bot-token: ENC[AES256_GCM,data:0kwJuFTjI7LXqP0alk3r6q8KnKXI9budZUebEg2c2pxaaY4hGv62p3U6CrM3/v2Xt8snVUNm/ftjH83CQUQEEw==,iv:VsHQTinRt95AUHIY7RCIaovLDgfaJnj+L4hChHIZrvc=,tag:oKUb4+pMNLsJFSR6vnWqRA==,type:str]
    public-domain: ENC[AES256_GCM,data:gbzhFRygQdT5QewSS8L9C3Nd7hyn6SScKZEQ8Q==,iv:xMsOXm7pYKcd5m0UvYLkRjQJstip6fGu3Fa9sEastfM=,tag:46KCCdQzFeg2EDWTrF+nuQ==,type:str]
kind: Secret
metadata:
    name: sleepy-bot-secrets
    namespace: telegram
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYnlIY1RnN0pDbmhtbVN2
            ZHpPY3o2VzhWRGVaWHFDV1VMOHU1LzVTV0I0ClVacW1DWGVlc0gvYmtGR0lQazl0
            d1J6S2Zxb0F5akhVSE9INlpsM0hnaTQKLS0tIC9paTZUa3o4YWI0Wk54YUdJOWxn
            bnAyTDhyNnBFVFNuZElRcVU0VUFzek0KMAQggEI2NWCSngJ0Q2GfZbIXPaEf18Xk
            cEdXXdJmY5gmFk9C+S1kTvrD5QBkbEXgGLlneAFs4JpaZG6q1TKOXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T01:35:31Z"
    mac: ENC[AES256_GCM,data:HS5X0YDVWg6Xpdtfp7Wcw86Ha3eT+dXvV81mQ13JKyHxnlunQidpBQ5BqYqLVTjcnoBaPkQBkmKucfQc2bjiaByLZBWuH/mVFxS9BsLBMrF/Z3k7ZyjubBOvATTdZtxMa6zPbgqlg1ovujr7B+2wvpy9ROk7JtXcD09hurC95FU=,iv:L/Py0RB6v3UyCAFoV3LNtVlXlLubBDY0Fk+UwhRs+Rs=,tag:5SxuTcBJP/hxdD/Hspb3aw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
