---
apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-cm
  namespace: palworld
data:
  PUID: "1000"
  PGID: "1000"
  PORT: "8211"
  PLAYERS: "4"
  BACKUP_CRON_EXPRESSION: "0 */1 * * *"
  AUTO_UPDATE_ENABLED: "true"
  AUTO_UPDATE_CRON_EXPRESSION: "0 10 * * *"
  AUTO_REBOOT_ENABLED: "true"
  AUTO_REBOOT_CRON_EXPRESSION: "0 */3 * * *"
  AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE: "true"
  MULTITHREADING: "true"
  RCON_ENABLED: "true"
  RCON_PORT: "25575"
  TZ: UTC
  COMMUNITY: "false"
  SERVER_NAME: "Fabler"
  SERVER_DESCRIPTION: "For friends"
  DIFFICULTY: "Normal"
  EXP_RATE: "2.0"
  PAL_SPAWN_NUM_RATE: "1.5"
  PLAYER_AUTO_HP_REGEN_RATE: "2.0"
  PLAYER_STOMACH_DECREASE_RATE: "0.5"
  PLAYER_STAMINA_DECREASE_RATE: "0.8"
  PAL_AUTO_HP_REGEN_RATE_IN_SLEEP: "1.5"
  PAL_STAMINA_DECREASE_RATE: "0.7"
  DROP_ITEM_ALIVE_MAX_HOURS: "0.8"
  EQUIPMENT_DURABILITY_DAMAGE_RATE : "0"
  COLLECTION_DROP_RATE: "1.5"
  ENEMY_DROP_ITEM_RATE: "1.5"
  DEATH_PENALTY: "None"
  BASE_CAMP_MAX_NUM: "128"
  BASE_CAMP_WORKER_MAX_NUM: "25"
  BASE_CAMP_MAX_NUM_IN_GUILD: "10"
  WORK_SPEED_RATE: "2.0"
  SUPPLY_DROP_SPAN: "20"
  PAL_EGG_DEFAULT_HATCHING_TIME: "2.0"
  ITEM_WEIGHT_RATE: "0.1"
  ALLOW_GLOBAL_PALBOX_IMPORT: "true"
  DAYTIME_SPEEDRATE: "0.8"
  NIGHTTIME_SPEEDRATE: "0.8"
  PAL_CAPTURE_RATE: "1.2"
  BUILD_OBJECT_DAMAGE_RATE: "0.0"
  BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: "0.0"
  ENABLE_INVADER_ENEMY: "false"
  DISCORD_WEBHOOK_URL: "***REDACTED***"
  DISCORD_SUPPRESS_NOTIFICATIONS: "true"