---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: palworld
  name: palworld-datadir
  namespace: palworld
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: hcloud-volumes