---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  serviceName: "minecraft"
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java21
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minecraft-secrets
                  key: rconPassword
          envFrom:
            - configMapRef:
                name: minecraft-cm
          resources:
            requests:
              memory: "5Gi"
              cpu: "2"
            limits:
              memory: "7Gi"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          readinessProbe:
            exec:
              command:
                - mc-monitor
                - status
                - --host
                - localhost
                - --port
                - "25565"
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 18
  volumeClaimTemplates:
    - metadata:
        name: minecraft-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
        storageClassName: hcloud-volumes