---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - soulmask-soulmask-secrets.yaml
  - soulmask-ghcr-secret.yaml
  - minecraft-minecraft-secrets.yaml
  - vrising-vrising-secrets.yaml
  - core-keeper-core-keeper-secrets.yaml
  - foundry-foundry-secrets.yaml
  - r2-credentials.yaml
  - kube-system-hcloud.yaml
