apiVersion: v1
data:
    rconPassword: ENC[AES256_GCM,data:ydFSuthIma/n9CP+,iv:YOURs1OP4xi2hzixU4x4oVHLUrtFMYoP/uNeN8Ke/yg=,tag:v/Ar5QdmW8R8BjbWZGlB0g==,type:str]
kind: Secret
metadata:
    name: minecraft-secrets
    namespace: minecraft
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL1p3NkIvZGFFQWhmK2VW
            SVFWNHV2c0gya1FVaFBiUGFodWxhYnVvTlRnCmFKRWdQcThPQkdJeFU3Nm9GT0th
            N0h2L2o3VnFFekNCRnhLOGg0Vld6WHMKLS0tIGdtNVFPbzd5U2lqTDl5UnJpVWIx
            VFlHTkRPenVUVTFTQ0FheHNsWmxTeDAKE5Eo8dVi6lKSS8Li4irxZfplBxM1tP9L
            jC0WvNZKW32nx/er62RLWHw8djX3GrW6dog5ktP8DBUKZAOhQRRr1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:27:59Z"
    mac: ENC[AES256_GCM,data:/IEWDp+xQkITEIpEohsc2peRuGim32GMHDa2THA26P0O9TjfZrF4t9WmPuF9DVn2qKV5SnWyaOcWrhI1M4ql2yOZ5GucgtIm/sV30M+imsQPaxW0C0Z2hiwKd+1ZledYz6YHMAAcsuS+YLzlqX/8DEyPPTzVuow5jl/TNsq2IFc=,iv:J4nF1kWrrsSD6VWeJBhppAVIAD+L4tz4GCBtyI7xNa8=,tag:pxuCI/u/t7opPMPv6KC9TA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
