apiVersion: v1
data:
    adminPassword: ENC[AES256_GCM,data:NCLYhuN4Sb5lGX8pfka6U5sDfR2zszN4hinPStTEJpPJJUV3QA3Pg5bjjFGFzfyknCRa+YGRy/zmqF4g,iv:bNYWZPyarD0rpQWjeyXpto9EYp9+4VeSXMFT/2QCp+I=,tag:cRWCz7WF28JJsStr3V8ljA==,type:str]
    rconPassword: ENC[AES256_GCM,data:i77V8CEeklG0TTsNFmgM3Ax0d7HN+0PMHnlW+VbCCougfAFdfx5k7VkUnaAbL4q6l3/EZlqZ8yk75GwA,iv:uuqvPd9uZ7VDreKJWFR2LDzR3LzLGXB2OxCSHukbagM=,tag:ZSJyaElTFtyM0ZozbA8VYQ==,type:str]
    serverPassword: ENC[AES256_GCM,data:CjoboVcWNRAH3VWd,iv:qUaHVz4b3XHUf3HkXQ5XTCrV1Ddvw+ypT3z9WjqhLfM=,tag:fGEtBGBbbKocboQcooeoOQ==,type:str]
kind: Secret
metadata:
    name: soulmask-secrets
    namespace: soulmask
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZ2hHQWprcUU2RHh2TjVY
            ajZmWjhPZTdxSkpBZUVCT1loRlNDWjQweUhnCkV3Sm9YWUFDK2F3cThYLzhqcnpV
            Q0hrbXRxY3doRStWOUs2MnMwcjVkcHMKLS0tIExhd3RrSk8rMkVydlBmMzlZMFND
            ZFhFNEJ3OXJXT0JPZWFNZXFOaGdqVlEKBuA9KSP2LH/rlh+bxLlxKwL3IhQ5TMwK
            EXSpoawkjM0TJZw7SxOiMjLeroL7C8e1HbZ3z7hAfyzgvopkc9XgRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:27:58Z"
    mac: ENC[AES256_GCM,data:jxAgPeMLb3K+lOOt+AFxgVvFbrwD26m4GYijZjISkxn0y9tKkJqBl1TuqYGdiJc0PVe7ZnBjSOA4KjmNmzFd9mQWXPHNdU4rQZNjVBbVCJGz7QFPn/4InsrX2ZHjocxRJbBDbDyWicrhW/F2dtmRZwjar56eppUeL5AdmuTd1/k=,iv:XaqHnaJ1EpsCKCfTKv4jbz+OQ6WokEhzKqzH+QLIjuA=,tag:NrQaT80/8y5b7c9W1AoXIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
