apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:2jnWGMOfz+bfJ5HMQ3mkchWxxkLH2s5BjDCZlB7Ze4ssB42BH2KQFh7YtYCvRdzC5O5SZ99AjsvEfhQ2dgBWA1XLiaEyArT40wMEmFAXolaTqTZfniQaBjtfaJ1EeV18seAGYOMK4D0X9y8foDmVca2ViqWGPLTI6cEJWUu0/1lnLJy94Vxg/lJLQ6Lo6B8r/yaV080NLfLMIftDUwIXvX3YUEmx91DFAK6nmHKfB0bOQWq2+66/iryHUSr1vutiCMyy8ChR2rSOAIVKWPOXJU8PPX60Nnl5k3ikUbI4z1uTWzAG12RRZEHS+lCcmT1z,iv:BHSMYIydGNLEkwa4BlVdefimuCR70c/uWkEGtK/YQiQ=,tag:YSeLXGOu/zwhyCghA3G/fA==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: soulmask
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTWxMOUFZRnRxUmxGOWxn
            UlF0SG1pb1F2QzkvMkhCdmE2aUhoeE9icW1FCmNhcVc5aDBUUEtCWFFCbUN3SVVH
            UnJ3ZEg2c1RFdEg4N1JlU3VZMk5zc1EKLS0tIFNlSmRSdWc5TUxBYXhpQ21mc1Fv
            WHpWTG5HQytqcjgrc0ZtbStVbGh0N28Kjiklxyo1Il5e9eQkUIOhylcFp4iaqnsR
            sJqyfW/hZUt1x/wQ+XRZZRAxBXDIYren1V+VDmwUVDm3HUrYxHsJuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:27:59Z"
    mac: ENC[AES256_GCM,data:9aOul/sO5sRJWKeMIMyhxZoyohS3D7gJf7NXz8vX4KpiBLZKjAQgbKUntER42TO+xNXjS0nWlF7ruMxqB8fziFT6270vrxMjQ3ZFn1XkYytr+yDmWIeWLJxz0MiqXArR0sAkBhd5iP6LtTDuo4WIg/SFNL+hUXVAPgvyGck25Vw=,iv:oX60RXsvpe0IE/75L1cv7x3OysFKmNgE4xvJM4L5kxk=,tag:wy4RJCje02HqCAr/9rCqfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
