---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes-encrypted
  volumeName: pv-gatus-data
