apiVersion: v1
data:
    adminPassword: ENC[AES256_GCM,data:ZIpPpvN6An45nl04,iv:2TOaRTgtEo5bwqkvWFgr1y6dIO3xtDcBubqXNGHJ/Ss=,tag:JyYPGbloaATuExgAbe284w==,type:str]
kind: Secret
metadata:
    name: alchemy-factory-secrets
    namespace: alchemy-factory
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N1ZiWlJodnMyQWpWTWxR
            amVTT0pyRWZ2b1FCMlFjQ0phZ0NvUlFrbFZNCko2M0R1NDhISmplU3lVVnBKdGNJ
            Nll3VEY0cTQ5dFY4RndIRDZMYnFnYmcKLS0tIGFqakNxdFVLY25hOEtYdXNmVFFH
            M1RJc1hGTjl6d1JscTlRTmpubXl4K3MK5hIN8uk7icHwfROZc53Qrb5d2baobH+7
            g7vLFmv+oP3MBk9X4hh+QSh3ntLoPkeMXbCIxz79ERyBEhqN2NG7IQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
    encrypted_regex: ^(data|stringData|secure)$
    lastmodified: "2026-09-08T20:18:00Z"
    mac: ENC[AES256_GCM,data:u5adTy9vKK4t7pOHVq/+v5vPSRbZRIryoH79ueaf2WXrT1cvOQxQ1SuPSPln5uh3FveRhEsWtNEC5r8wCrrQ+Jhuzn2WACkzBOLC6HlPorslvm2naagGm6KXqZWcIumuUYqDG2l5GTNs/L3QgHHQ/zqZCnJAEPxH+g2zOqrLEdc=,iv:ZedFd86xVVancXdKQxrc1u/arsh4ziR3E+2HLoYT9S0=,tag:Fj1RDX3NYBRNOnG/lDVqjA==,type:str]
    version: 3.13.3
