apiVersion: v1
data:
    adminPassword: ENC[AES256_GCM,data:Z/BCGDPEd+oSP0MXLwS9YZcFXUW7tGNli8zZCA==,iv:erVGHyXed11ozS1IlQk0FoNTedVlDtvfI41jvnnPjo8=,tag:OvfYzyATWjqBcJwM7ZydJQ==,type:str]
    serverPassword: ENC[AES256_GCM,data:eA/aAceUbKbOFSqk,iv:Ux2YGOXxepkSPB3kubCMVdTLDFshlt2g4ukq3cI6xHU=,tag:hNFfw9bXRvQ/EBjDOV66Jg==,type:str]
kind: Secret
metadata:
    name: alchemy-factory-secrets
    namespace: alchemy-factory
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3alVRdk05WEcrY0N2ZFpC
            bksxM3NhUWJhTmQ1SWZGR3BJZEhHZXlIZkEwCk9JUTUzb0hQeUJ4empXejRMWXBr
            dU1odUtzdTEvRVhnbVZDZjBJUEJlMGsKLS0tIGxIWktUV1dxZ1dTMUdGbXFoYXlL
            VUloUUlKNEQ4QzBsbjl6djJjbmRESVEKu/5FGa6gDA4Zu5NHqiJfwIO5EjA6DZ5b
            2T6B2wD0HC8wPmstl7B2mTGCPLH5T5Hgy+cLHJX1fgjAc7df6zTw8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
    encrypted_regex: ^(data|stringData|secure)$
    lastmodified: "2026-09-09T16:36:57Z"
    mac: ENC[AES256_GCM,data:ot8eVZhT/wRHh2XJq4n8TME3mqtoWGBpGTmA076JT7ZQZKa2dVcK3DBs6BcbTGuDWrwzMgtlw/MV96FYCzOeBZM3mv6Zfw8HIRpuWydqLmpqLOyHtsSp9n4C5sRhVz+VYkZmJ2VPMRX863S/bTmXhAk0ojWmqZ2GVNffP8N3czs=,iv:zbN+KUoMM9iHxvsdXJG7/+aLGBvYq6T9XRDhji++niw=,tag:/qfTNmpX3O8YkwNnfc8eyA==,type:str]
    version: 3.13.3
