---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alchemy-factory
  name: alchemy-factory
  namespace: alchemy-factory
spec:
  type: NodePort
  ports:
    - name: game
      port: 27015
      protocol: UDP
      targetPort: 27015
      nodePort: 30015
  selector:
    app: alchemy-factory
