apiVersion: v1
data:
    modioApiKey: ENC[AES256_GCM,data:ppdipH7YG2/HLPVcMkZtEdc3giWiUnrYZhncWDb/9M0WPAxOFiPhwh3CUCQ=,iv:mpO6gXSS8ZP/2xGemd9/YzDZmeHApPOMi6n6isAPLx0=,tag:YOBWk9OmffC/ZfzSS8D7RQ==,type:str]
    modioApiUrl: ENC[AES256_GCM,data:fHuUE0mP6MgrYo9TAjEIM/S1CyaJwQhdM1XCQ6Xt1zKsDWzaF7yM3rahggk=,iv:SYFVHLiiRbSUgaOaEqJsAP4/oYfErVUjtiU0iqWs5l8=,tag:K+B+UhPrL9gJIcfMmVwFbQ==,type:str]
    serverPassword: ENC[AES256_GCM,data:QbTs7YM+Cmm9ce5i,iv:IO8b1oUBpyxCzTDtuRpDpCkxosYQRz5mjRArlrqVeY8=,tag:mYzjhKVV29eU2eurWO3owA==,type:str]
kind: Secret
metadata:
    name: core-keeper-secrets
    namespace: core-keeper
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdDBzY2ZxMnZhcW1EQnNE
            VkFKRGw1YlRuVlducUFqbjZ1V1ovTEFZQlR3CitVWUZuYVJSaGI4TWdUUEtpRzhS
            YTYyUk5xcG81b0tMOStkdGhvMFcrSWMKLS0tIGV1aGIyTkQ5VlZ6ODZoanRLT3Jx
            dndLWmNibm13RFJxc2MxVnpvbmJMYjAKFHiWyWB6GUnGJH9fCMiGPF3e0jphpKLl
            msdqNF5yk2z9uwGNXuNS/twJnPlhi/jK8Qe/m+K/pfV9cDLFZk1YIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:28:00Z"
    mac: ENC[AES256_GCM,data:tLWYPepZ7jQX2kSIbAl/RHPgJW+Xu2Jl5iFRVQUPV9e1/zktxI3SUd9fD04TkPwTUgSf3o/SN73QAgnSfRnS1CebOPawqq5UGz8ZHi9UiiEV6CG1L5U4GSgkBLZXbvSmq/8eEm0h1x/SboKuaMa6jIb8GYwhMWXvqa1zYq8H9oU=,iv:+lgBq7YL2UPg9J0ahPrTe8N0Qh2bvTPhjjOOTz9lVjw=,tag:UnFb+kaIKZ+YatI5jp9GDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
