apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:Hjz99d8d1/dS7Uvpem46Whni/T/YBkTCeW1Er27Gh9/BMmqHAoFUYx+sNps=,iv:AOgLlSQJAPShYVNpOkY+33/+5wi0acHmgq5MJ7edThM=,tag:UNjaOmJb3Wy6kD5VpTqamA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:+yhudg20rDdMGZYI572FbmjdDSnxssGsfPeGF9M/p8iDBtjyDye15F+bu0cuUoMiR5Hy/oEmdQHm0V0wU3RrztZ6gRKJnzvRqye/yQRplep32j+0B6/oZQ==,iv:KiMMrk4kXHVUaV2LxZ9J6Xp4I2bq0xb90S/Bd+wmDbc=,tag:fv5az1Oh/ojB/21qUrik2g==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: booklore
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaFhvZDU1RGwyNXhDZHRk
            UHlXYWpnR1FFRkxqS3NJZnZOTTlzQ0hEUmtNCnNkQ045WnFQVWVsQzVKMVBNNFR0
            djhBZWNEbDlrQXhFMHRIY2pGbkRUWkkKLS0tIFZHc1YyVDN4amxKK3NOaEl2am9N
            NCs2bzE0dkduQ1phcjlOSWExalZIdHMKEI7ZZnYWNiru4KYCtUcRE/a5FYE2SaoJ
            cUgHH6G409HJKcsNs991BZr7F5HhFBfCiCYaLMM2CtjntrT3XHvYpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T12:41:00Z"
    mac: ENC[AES256_GCM,data:W0q1pXdY3BaYbAguKl2pilbvy+noZqfLdpG6mP9KNB2DA6VonNIDa24xIOGD0TvV6YmhtoQnZPnVz9cGcD9MbWyG8cbR/8bDbX26PIWqDvjhut65U4QmSmyhrayR/c735DXPgegdFBtreAYDMqEDV/+a9Rg+WY3T2MBA+B7VOBU=,iv:PhpT5Ss7rmSxG12pe2uTdJyfHOf0QGIaXrpinZ+cvPo=,tag:FzLEAuWa5mqzI8AEiggAkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:EzzDuQVFc0d3l09VChW5j+dUi3yFX8mKcGBPBjm50daGGDXMPOy+y4mOuec=,iv:8CYo/DjKlB/q0609XzFeFtiKxgLgp/7XpjmSCRQksqE=,tag:7F+cghDclqwg6jr/QDcu1w==,type:str]
    secret-access-key: ENC[AES256_GCM,data:4NQda8fAz9ZRRdN89L1u5clqzMB9Z1Kzmm3ywqgB64X/nAJA/ZmScDOI4miAm/qF7t3jeVc0+tG6T+jbWASEumuZPhvXnSGdR8/l1penwuVnqeNX+qegqg==,iv:OLoCrIw3n9OJbZJUeVhq5sRiSO+ZEbO1oob9D5vvnmM=,tag:LnZAGhJf/wLt5ovSnGLKRg==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: identity
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaFhvZDU1RGwyNXhDZHRk
            UHlXYWpnR1FFRkxqS3NJZnZOTTlzQ0hEUmtNCnNkQ045WnFQVWVsQzVKMVBNNFR0
            djhBZWNEbDlrQXhFMHRIY2pGbkRUWkkKLS0tIFZHc1YyVDN4amxKK3NOaEl2am9N
            NCs2bzE0dkduQ1phcjlOSWExalZIdHMKEI7ZZnYWNiru4KYCtUcRE/a5FYE2SaoJ
            cUgHH6G409HJKcsNs991BZr7F5HhFBfCiCYaLMM2CtjntrT3XHvYpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T12:41:00Z"
    mac: ENC[AES256_GCM,data:W0q1pXdY3BaYbAguKl2pilbvy+noZqfLdpG6mP9KNB2DA6VonNIDa24xIOGD0TvV6YmhtoQnZPnVz9cGcD9MbWyG8cbR/8bDbX26PIWqDvjhut65U4QmSmyhrayR/c735DXPgegdFBtreAYDMqEDV/+a9Rg+WY3T2MBA+B7VOBU=,iv:PhpT5Ss7rmSxG12pe2uTdJyfHOf0QGIaXrpinZ+cvPo=,tag:FzLEAuWa5mqzI8AEiggAkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
