---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booklore
  namespace: booklore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booklore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: booklore
    spec:
      containers:
      - name: booklore
        image: ghcr.io/grimmory-tools/grimmory:latest
        env:
        - name: APP_USER_ID
          value: "0"
        - name: APP_GROUP_ID
          value: "0"
        - name: DATABASE_URL
          value: "jdbc:mariadb://mariadb:3306/booklore?createDatabaseIfNotExist=true"
        - name: DATABASE_USERNAME
          value: "booklore"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: booklore-db
              key: mysql-password
        ports:
        - containerPort: 6060
          name: http
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /app/data
          subPath: config
        - name: data
          mountPath: /books
          subPath: books
        - name: bookdrop
          mountPath: /bookdrop
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: booklore-books
      - name: bookdrop
        emptyDir: {}