apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Q+aQM1zX9oK5uyHtno7COKPke/rxr+6iklodTkWw4am3iWgO,iv:Hg+RAuqVa4y3q5c4Y1jCQWzaxm/OpXsSvfmOujjTLdo=,tag:DnyssAx0ltwnXWq9ZSKwDQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:aWOrQr80HPvVesDM8Jii2k+cn7i16CZA/DmnfWZN9Ac=,iv:jMXG8EgZ1RolbazEWacHyC+WIHfIfqPXWIUfTAbLDKQ=,tag:bG3/5rT9b724uX2eO8EbJA==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa0tCSDFBTzhkbUZVUS8v
            bzlhVjZlTmtpQURSd1JVYkdmYkFmcVJGaGtBCkpwQUFCVmh1NFhQZTA5d256NTFJ
            bVpDSkI2WVR1azdRbzRSbHdTQzVmdmcKLS0tIHhyeVhKVmVLd3dYS21lL3htbEh5
            VFJSSFpraFhodTl0NFVVN1dabXYzeDQK8fCb6ncAmntVaaqvM3VSx7FvuwU+tIhW
            ygrX+MokP5GUwW6N2IDoc5khcj5mEkNLJABtzW9fIHylJgrZQvRBfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T17:28:27Z"
    mac: ENC[AES256_GCM,data:/PFs8FA9ayubuff52FIxbYizKNThkfw6wXi/D+Oy/K/RY7IS//GxPPOPnHbjTw3fYetjjI4IS01DAThxRy0/AOO0YD/3QexhGMP8X2EgfYmYZNlInyFCudNu7VMgpJ3HJxp8cS35Ii9oIhb7HIdOTYddXt9uvqxS/GNELIO2GDM=,iv:ETwDi1P/nFN3AZt8Rw6E7oRe5du+EKQpCaBscI5ebQg=,tag:VUNY9Lh+As5I/KwGPu5K4Q==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
