apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:UnUreBs=,iv:LVpB7V7JQgVx1KCl1aiQaZaJpvxnZH4XijsTcr+wMjA=,tag:zPurj9yfovxguuFE6pUAhQ==,type:str]
    admin-password: ENC[AES256_GCM,data:qYCIdhziXaYgbOA3xeKd6mlJ3VahT7QQ,iv:Kootuz3saKuQLx7HXRtrcjoSGfX/rnyZRPRoG30MZm8=,tag:t0HpK1rdVpX8QaDjraNBbg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY0hRaG5PYkdMazVuKzRs
            SUNDYndoZkxuSTk3bDZqOWZYUTQrTjJwTkhjCkRZRG1rbHhTUmV0V2gxSFFtYlBa
            eUdBTkJvMFhDUjZDdlpSaytNTytuTk0KLS0tIGNRUFV3N0YwOXRnbmwzQmZBUHF5
            OTM0cUI5eFNWTUlrQ0ZBRzZIejFYZkUK/R74jTZvSbODEVCM01WJTaaqOFnFlkC4
            5scs234m/HykR6AiOMAUxioT5e7i2pCVNYdQQuCcSsjR3jpa5lRsbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:46:23Z"
    mac: ENC[AES256_GCM,data:vVvuZH+caTyp31LvNkFw658hEOnCDx6Ue5DTZALSceO76VSd9l9yDnYYqAHtrSCb/dCLTipw+2LrKWz/Hj7yQYOsOdkhJudn/W/D0GiDe7ONhHBm6H63nivJKzC+dO15vy65GBj/QQZaRUzc5PbbXMk35K86+r6JNCeRd70lBb4=,iv:0H4S0PXnAhB8ttL+mQViLGeTXAGD/GAh+gttmmB6UUs=,tag:qjEVwVTgjSr9edmbYck1eQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
