apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secrets
    namespace: pocket-id
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:EfiYo2N37fkpZhHC5173CykiC37ZWjrRU+VgJPz4FwkqxijWaj/iNK6W3/Q=,iv:sM0Hot1CrKOu/A8EwEsU91vHBKqjXjac0tiMWR4VTfA=,tag:CEwsj4bCvq5OLsHwKjJUtQ==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaFRJL2JPVnJJcUUxSVhh
            WkZuZDNhMnBjZVNEd25saDRhK0dKbEVFR213ClMvSXN0VXA2ZHpIR3RMb2lZRUgz
            U2RLb3VNRHpXS1FnM2pIcUxmTzNFSVkKLS0tIDY4RFJDT2NYSDBmT2pqbndwOC9w
            Mk5MdnRsWkNnU3Z6UXVxV3d3V1phOVEKq8NaqRIwtJShJg2cC1DFf7xH+T7PJj0b
            RdcyiXJCGmPwoOKesMCweIDUz6wtcpGfmbAllBKbNiPRQXoTWeD8PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T20:42:11Z"
    mac: ENC[AES256_GCM,data:2wOHcgYlTOXCfQ+e9Ls9J7G320dGdypvZQIOExsG7ZKyvxHw8qKaYvTrPJ3bgtUqRehCi0djEJiHeBvD4jEruRNomtOVmkr/uQSUjoWeEpNNiOs61vvl2atSpXUCEJgm100YTV397rnaRyYHnWzmYxqTHhIBQgJHbtD4Dz9KnYY=,iv:y5CLd/m8MRw92jhScXx4FS4qZQJwstmtXhxDKOGvLYg=,tag:Tjl8xQRDShFRE+k/CtkSRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
