---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pocket-id
  namespace: pocket-id
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: pocket-id
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
