---
apiVersion: v1
kind: ConfigMap
metadata:
  name: satisfactory-cm
  namespace: satisfactory
data:
  MAXPLAYERS: "4"
  PGID: "1000"
  PUID: "1000"
  STEAMBETA: "false"
  AUTOSAVENUM: "5"
  DEBUG: "false"
  DISABLESEASONALEVENTS: "false"
  LOG: "false"
  SERVERGAMEPORT: "7777"
  SERVERMESSAGINGPORT: "18888"
  SKIPUPDATE: "false"
