apiVersion: v1
kind: Secret
metadata:
    name: dragonwilds-secrets
    namespace: dragonwilds
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:G2gDaugUcAPjOHtPUMbd2G+VjBc=,iv:ERtpvmmOkKDKS24Y9EyEu3KN+K3AAtsv5ssqnS5vomw=,tag:E8hDyZTQfsgGUSl2CXgnow==,type:str]
    worldPassword: ENC[AES256_GCM,data:pcnY3Hg3qK0=,iv:bJTCDO3SZwnEPzh/+TKM9bgctuGUinh3iKqmVAO1b+E=,tag:5lQh8bLyY8r7j/bdqK3fDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMCt6Q3pzRnY5clRnVmpK
            ZTI0OFlLQTB0T1BEVVhVQkFMNVR0YTZyTFZjCmVLMkw2UkE5alJmY1Y5cEFNYWlL
            bS9ya3BHbmJXUUhQd3c1QWwyNFBXbm8KLS0tIFEzWXIveXVXZlJ3MGlxcFJhYmQy
            alhhZlFrVEoxU3dOMGd1MmFNU2YvWjgKe6RgwjxymKOlwH/366MTcQ3j9+6EhxKT
            IfOStUaXCZeyHWsdB2+SLko5W2yev5XWnsQmyo7TIVZoUpT7IMOmQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
    encrypted_regex: ^(data|stringData|secure)$
    lastmodified: "2026-09-16T11:31:18Z"
    mac: ENC[AES256_GCM,data:Rxdy1d+7SQ3JUrQD91wtpJA0idBhvs2MoHg0AeDfyRxzm5oQaiuluiYs0jLrHgdvLf9On9tqrVUKQGvWnib87zUFKpHuaNI0AOnFPzXPGa47kGmtBRaF8HKc3WheiydeNHKPkNllYHfo5NVIQNskkohBQutp88wDADcdA6BAGg8=,iv:UqyfsWVDC9BERlj4p7wDFwa9aMuXM4ZvTiu/i/YwwKQ=,tag:Vu96T9Q+ZbKnSRJC97GF/g==,type:str]
    version: 3.13.3
