---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dragonwilds
  namespace: dragonwilds
spec:
  selector:
    matchLabels:
      app: dragonwilds
  serviceName: "dragonwilds"
  replicas: 1
  template:
    metadata:
      labels:
        app: dragonwilds
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: dragonwilds
          image: indifferentbroccoli/runescape-dragonwilds-server-docker:v1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dragonwilds-secrets
                  key: adminPassword
            - name: WORLD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dragonwilds-secrets
                  key: worldPassword
          envFrom:
            - configMapRef:
                name: dragonwilds-cm
          resources:
            requests:
              cpu: "500m"
              memory: "4Gi"
            limits:
              memory: "5Gi"
          ports:
            - name: game
              containerPort: 31777
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /home/steam/server-files
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
        storageClassName: hcloud-volumes
