apiVersion: v1
data:
    serverPassword: ENC[AES256_GCM,data:G+hy+lGpLH01TvqE,iv:fVH2mXa+CF3Ce8/3g0nC4OAEiV0iWrYbLp1C6DljcRc=,tag:cea1YG+J/ZY98JTJS2YEbA==,type:str]
kind: Secret
metadata:
    name: vrising-secrets
    namespace: vrising
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSjU1eDFJbWQ1NGVrNWJL
            OVJIdFo2Smt3V1lKTEx6d3lISHdlZ1RCVHlvCng4a0ZNZ1VtWDFXSU1WTHFSY1Ev
            SEtMYmZQcGFBUm1WamI1SE5TNlBPMmsKLS0tIGF5dnYwQy9YZUhYaElWcDFHb2Uw
            blZEdlVNT2N4c3Nnb1lNZDFicFpzTGsK4MNoWU2jFfE25ah+ZnvZmIBAPFinWBra
            zm+TAXmdcgCO+EBcdVnrC8LuYOJF88bpIQK8qMxyFqtVH5iPyKIHjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:27:59Z"
    mac: ENC[AES256_GCM,data:jIoelZnXuEQEkVEor3VpsvHanr4d2RXi/FNEa5DmzhxSzVjo5zc3DaG88+IOiwxZrK5tZmbWSwez4DUDcFAKajMsJdqJE8fUmbmvsUTujX4NSfm0LC0vRnRSp9bkiF5p235K4e11WicfeC7/qERpnNKwEhjuZCy7EiAS2jTGwPI=,iv:O6M16mGi6oPM3H9+RhJ7v+JBXNNyroiLyq9GRL7gZQI=,tag:L2sDSwCmRpOAwvh7/Tim6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
