---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enshrouded
  namespace: enshrouded
spec:
  selector:
    matchLabels:
      app: enshrouded
  serviceName: "enshrouded"
  replicas: 0
  template:
    metadata:
      labels:
        app: enshrouded
    spec:
      containers:
        - name: enshrouded
          image: mornedhels/enshrouded-server:1.7.1
          imagePullPolicy: Always
          env:
            - name: SERVER_ROLE_0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: enshrouded-secrets
                  key: adminPassword
          envFrom:
            - configMapRef:
                name: enshrouded-cm
          resources:
            requests:
              cpu: "500m"
              memory: "12Gi"
            limits:
              memory: "12Gi"
          ports:
            - name: "game"
              containerPort: 15637
              protocol: UDP
          volumeMounts:
            - name: enshrouded-data
              mountPath: /opt/enshrouded/server/savegame
      volumes:
        - name: config-volume
          configMap:
            name: enshrouded-cm
        - name: enshrouded-data
          persistentVolumeClaim:
            claimName: enshrouded-data
  volumeClaimTemplates:
    - metadata:
        name: enshrouded-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
        storageClassName: hcloud-volumes