apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
type: Opaque
data:
    bot_token: ENC[AES256_GCM,data:x2yV6xpzFCyTFBjfmK91uyDW3RJJobSYt9S902ORyDaK2brKd4cQylorOkvctDnAT3MQ0hin7s1kraVIkyR9Ag==,iv:qaYV8Z/SOk/A1RM9VMPCCcA+zuwMmxlvp9Mc5vNvafw=,tag:8+t7a34yekMW2sKqrOoYSA==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dHcvQXN0NmlMeDNDbW16
            bFg2clNkS2M1bGN6MUZ3SThjdlVYR1NsdVNBClFXYkVrOWladXpKY1NNU0F0dWRm
            Z2NRaGFwODMraWJyTXAyRm5BMi81ZVkKLS0tIGlKRFk2ZWZWUDJ1R3dPWEpBMWpG
            NUFhQmRDSVV2K1ZyYUV2UTBtOFBFTWsKIMFFLYXC6MPJjzVnACsYXE3/E/ZBr5rr
            BU7akQ+NAJl8LJMBoUS1EAMttA70JoeGNfbLcM1zU+hp7kGBrgcZBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T18:26:00Z"
    mac: ENC[AES256_GCM,data:1wvQ3yaj19J+rHycBH4r6LkzZhVyhHR9wB7mAaMEh4Hzp6ZBbNXtxeMjYxjzvSreW3p6GclIR5XUKUg8FDhKVFu65cjV8YDbXkUp9eQ3b4S9bHWQEayWqrYMJ2vuELiAdsgW1xth8pHODFgSjwDDLzXTWro8EI1P9xOAKTA4mqI=,iv:zQ49PHStrou/R8KbKqoxIsvLve1qq+fa4cDrbnwnr7Q=,tag:LduHT07QgM3qNcG0KjnG0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
