apiVersion: provisioning.grafana.app/v0alpha1
kind: Repository
metadata:
    name: tools-dashboards
    namespace: monitoring
spec:
    title: Homelab
    type: github
    sync:
        enabled: true
        intervalSeconds: 60
        target: folder
    workflows:
        - write
        - branch
    github:
        url: https://github.com/idarlafish/tools
        branch: main
        path: grafana/
secure:
    token:
        create: ENC[AES256_GCM,data:wHWl+DM7150AE1s3xXZNbkS3VFbiaUg0BmFw8/NoRuMR2d1a7CJLrkFR0REp30C4t7XeeXbLkHqUNvw0tPDRNN/Xd370gQcs0hBWob2f1pAK0JlXxPCI8LzKrDXW,iv:Pt7Ixh2xMuOIwC6LsQc8e4dL7aIgke8NLXnBtvZkXWs=,tag:9KUUcGSPsJU59r26GFg9Qw==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRWE4THNYekZLZWRvVUVw
            N1BMM3FjMjRsZ3Y5ZUVQaXRidkRVc1BwLzNvCitxWmU5dEQxWHYxZ3VxNm9GeUxv
            TGdlL3lvWUg3WVpkT294V0ZLQTBYQXMKLS0tIG5OUVlXV2ZLQ0VEZTNQdElWeTY5
            V2ZSZlF5UXlBdUhkOUxabzdhZDdzTzQK9Tax4AtyOWdYaIdTNxY6yamU6v+fSEBJ
            ap/f1hUg4wGusZ0UvZwaA0pSPH0ZUXiG8T+SeidTPHyPJWe6PfdcPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T22:42:54Z"
    mac: ENC[AES256_GCM,data:Pxq8tbgWAtNtVK7l2LuddNeMhRW39p+rtYz0hqN7LhQflFnpCARj8Hs3iUhFAme6oKRdOOtnOdldxBLFRZ6dkCrhUKjckSlkTq8cF4z4+2cg6Lr2ltBZy1quMF60qCflVMCJlzfr9fJyWT8WWLfg2GfGAKbDU8Opw8VCkKnZbzM=,iv:jRAiIX0iUT+odQhIuAoKahcYEzuKxV5SOmclpjisSyo=,tag:EMkpj2cWzOJf7xV9lmnuqw==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
