apiVersion: v1
kind: Secret
metadata:
    name: xray-reality-secrets
    namespace: vpn
type: Opaque
stringData:
    uuid: ENC[AES256_GCM,data:xVYBOOKKPYBPcVG1Fdu4aEhoPEwwRLgicbl0x3acbT5fQyC+,iv:dqlbKa/mJTdiSOyt/nRoksILZ3DD9h5Aap/paMDluV4=,tag:hhNe3PMk1nLT7YgHKwhmTA==,type:str]
    private-key: ENC[AES256_GCM,data:qc6K0ysnzRg24MfqCMI+VSo7OZYlgT7SQhGpzOxKuu2G2O72xvRZcNG8jQ==,iv:o6SGYngA8kKBjlTf638ztJoFKctxmOqWIqbrRT/uo+g=,tag:9ES4NTzUOJbVVxVtlIc+tA==,type:str]
    short-id: ENC[AES256_GCM,data:ohj/yytX6dOR62RW0fz5EA==,iv:vkuxYBCo7uNRZF9y+GZOju2YL73SrfSdL49oJjYPP5A=,tag:bcWmiJtfJbtG/Dnw3y1xGw==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOUNVZGdHcTE1bWUzOVVs
            dnptZERycWJBS2hyT1pSUFg0SFVpRFo4Y1F3ClJ1SythQWt1citmVmNVYkp3b2oz
            Wkg0bS81N3FiQ0RSeGhicGJOWks4UTAKLS0tIDNtQjA4djF3VTRMVGhmR1owZGx5
            U3AvTUs0UHZ0amlrUnpWOFcvc1pwSHMK968BLKPrr6Harbk7GiALq/UyjidP2SzC
            Z9HWoxU3I60f2KxWVXfeq0b1UECG1F3LzO4xTwB+q6rMRYx5hrke3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T14:42:17Z"
    mac: ENC[AES256_GCM,data:zA9fkytvmNH40GSEJvCph0mN6HpTszQ+b26zrNvpexT0WXe/RFsdwQVAe82dnN5gpfGkJjITFepqVOUa5eVJhTVQSW3sRo/oRrJH/DHx+CQHmVH1LbURkAQe7lvK61r3i2IHzx+i1CG5OqyH4Hc50hLJPHva/bDOhGZV6/hT/YM=,iv:QDdH/FWohg9j/MNY7/3x+Rw0zZfOBKYE+JLgSj/MO6c=,tag:VL08/bE4/FB70Av1Xkzl3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
