apiVersion: v1
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
type: Opaque
data:
    token: ENC[AES256_GCM,data:whyADBkAUkyhWXrXLOFm+8fln5FA2U9UsseMmf1Rb0ze2WAFGymbb06MAaANn0mKGM3bZoOJmsCFGxAX+GXJlbg8sOd+TKKpP7ilkZWXSxffD2n29Ub+Xg==,iv:eOKdcgK15kEym9wQOrhaL6/fF4on2rindaCDUiJlVkw=,tag:F1svXkueXDCho/lDirwhfg==,type:str]
    network: ENC[AES256_GCM,data:dwdG63u2AwgLgrNH,iv:R9tCyOi3JjCDU0uRJuCZFDg+lT4jz7s43P9+OCHPlmc=,tag:S7OcS0NOiKuy/CjmbQLkRg==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VWtBZThic096Uk9QM3hn
            M1BnRi81cTJnZGNLSG9kL1JwV0VJYUpIVVM4Clh0RVJPUDNZVUxFbUlmWktIZkdO
            VUdWTk9lUFo3bC9LUy9QbmU2M3JwVGsKLS0tIE43RmcxajYwb3V2ZWQ3eGFUeFJT
            Vk94MmJtVWtQeE9RQnBsTTRUYkZmd2sKzAQjRhLJiP/ytLZslWOg0cQ0uKIY8HoW
            7LqVLpJ/O199jasIt8FZRaTjhrKWFYXEEGwvB4uDIG8NHizaF0QSEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T16:19:35Z"
    mac: ENC[AES256_GCM,data:TL5AAJ8y71VG8C74reMYwHHixsUm1cUXZZj+Rs3M2h7/M7k6q/Few9Wttbf9H567IVLnJMa+YS/LLXaGVDbbvq+B3N6VYT1DB1QuHY7sf5d7iE9rGeUDncHGq7rBDkJIXe8PlwTgsDN1FPjJl57zCJ0j91HY96eweQEGFdNBKH8=,iv:L/ks7c82NgxgFh2KU4uf+fWdK0D0ChVYOSRiZRgj7xw=,tag:pzXLwkrbj9NGO8CBz75LsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
