apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:axp3sYYaVpfOJSjVTG3k1NJBKxjbWwmv8EjPiqva4yGZw+ALDXx90IFq2KA=,iv:jaYnCcyxL3/fDlsnUfjtI4bNdgna8KQcJrOV+6By+k0=,tag:mwBkTqoVIaKEz230O/wTjw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:cYiy5ijB0AcKpC0XkSABoOMe9341heyIWIGYdhsCHZfFqqAL2QO6DcDNYD3vpcb9b6P4rDxCT/RSUonnET9KKhvnrpTn5ODJcIcARvWnVLzf1uyspdsxrQ==,iv:YKqH1EqJVOUFQ2oEy/m3GwxEtwbCHJosCOAS1gjVrTA=,tag:rGWnlPxSR1fgXsQQgMbTig==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: minecraft
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WkRlUHNESTFLK3g2emZE
            S3llRk9wRjd2Q1h2L294amlIVklTeTRzc0M4Cjd3YjduNWlsbTVaaGVBVTVTWE01
            aDlSSGV3SlZZNXIrUkFjeHFDKzVaK2MKLS0tIHNwOXczUU90ejJkUkRpeDRyajZD
            eEdLM0Z4TDlEM2tQRTN6bXFQaHpKVk0KYHpfYmR02JNTGcCQbI/3xTbdw2GHbXGs
            0mNUrW7H/oA7Jt0oPltDqyyK06ImSye/tfhdBCL/h6NKUjPnIpiXfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:54:38Z"
    mac: ENC[AES256_GCM,data:KzNJ3PrOMaCmy87KM3wCD2Sp+f59njh927CLO3IbLgB7E/TeY3Nfe8y61/CpSSo/taTGgLmYGFqpKp7EvZwddJL9e56adiGeDtlOQFUqRUhxszO1rzD2y2YQPOlOpsQ+0sbdnbKbUZQsMylLx6Vg+0KgHuuuSx6x9OQVmMTnf2s=,iv:Rytgk6tG0oEheIMzzSGSLb/5ipocEeSp151ScksAE2w=,tag:vAhSZcXJfV0xml4UDBorxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:296qrdR8hjYqmb4nclTG8+h93ntJNJTC/ZDcPhweQ6npT1K9TJPPQdLNuOg=,iv:oA4+pKW1BCNPTla6GiD+fAiYSTDHAz4gj/JLmROWd38=,tag:Fqsn0ZpiDKA/ZocHoFz5MA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:aUDCYGs+g44hfdFnNMwHW0umSOetrUoSz5CJfJlvAI9llYMBzTNm5d4OMHddvrCGJXGA7R8Yy4iQ+C65y6uiAkfVa6kGlEJ55gcpLWoNLuos1r2te8ZMzQ==,iv:d9nO4Pw/CRFILunBBYOhyUPdHLHIjb/6q1gbOd9HhpM=,tag:kbPIeIEi52HEJoEwb7Zk9A==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: vrising
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WkRlUHNESTFLK3g2emZE
            S3llRk9wRjd2Q1h2L294amlIVklTeTRzc0M4Cjd3YjduNWlsbTVaaGVBVTVTWE01
            aDlSSGV3SlZZNXIrUkFjeHFDKzVaK2MKLS0tIHNwOXczUU90ejJkUkRpeDRyajZD
            eEdLM0Z4TDlEM2tQRTN6bXFQaHpKVk0KYHpfYmR02JNTGcCQbI/3xTbdw2GHbXGs
            0mNUrW7H/oA7Jt0oPltDqyyK06ImSye/tfhdBCL/h6NKUjPnIpiXfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:54:38Z"
    mac: ENC[AES256_GCM,data:KzNJ3PrOMaCmy87KM3wCD2Sp+f59njh927CLO3IbLgB7E/TeY3Nfe8y61/CpSSo/taTGgLmYGFqpKp7EvZwddJL9e56adiGeDtlOQFUqRUhxszO1rzD2y2YQPOlOpsQ+0sbdnbKbUZQsMylLx6Vg+0KgHuuuSx6x9OQVmMTnf2s=,iv:Rytgk6tG0oEheIMzzSGSLb/5ipocEeSp151ScksAE2w=,tag:vAhSZcXJfV0xml4UDBorxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:LjPUM/gOsGptNiMQYnI+PmXCX754SfpEPZ01QSPwXZVTHGB/F2XKi8QuqAw=,iv:5oLQ+nOHADJzLrrDOGVMRLlqGTGVu9994Y3NPN23I8w=,tag:UQKHEVuHdiVDTyn6FkN/IQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:4eHFV3/YK6/h7V+IC7iO+CjarFZxKgcqWJeUSsbkJhr0CNYPAyvH/Z7VpLfg8eu09cozSBbHQVpq+zLSmUUIV9xxhyIzidoPyEMnrzEKhuYn6qQl0vHMag==,iv:xq7yYT1bkMlo6B/nre+vUyliSxBLnYj5UKDZcSA2LcI=,tag:5xfp5flBJOqeF2qrxAq2wg==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: core-keeper
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WkRlUHNESTFLK3g2emZE
            S3llRk9wRjd2Q1h2L294amlIVklTeTRzc0M4Cjd3YjduNWlsbTVaaGVBVTVTWE01
            aDlSSGV3SlZZNXIrUkFjeHFDKzVaK2MKLS0tIHNwOXczUU90ejJkUkRpeDRyajZD
            eEdLM0Z4TDlEM2tQRTN6bXFQaHpKVk0KYHpfYmR02JNTGcCQbI/3xTbdw2GHbXGs
            0mNUrW7H/oA7Jt0oPltDqyyK06ImSye/tfhdBCL/h6NKUjPnIpiXfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:54:38Z"
    mac: ENC[AES256_GCM,data:KzNJ3PrOMaCmy87KM3wCD2Sp+f59njh927CLO3IbLgB7E/TeY3Nfe8y61/CpSSo/taTGgLmYGFqpKp7EvZwddJL9e56adiGeDtlOQFUqRUhxszO1rzD2y2YQPOlOpsQ+0sbdnbKbUZQsMylLx6Vg+0KgHuuuSx6x9OQVmMTnf2s=,iv:Rytgk6tG0oEheIMzzSGSLb/5ipocEeSp151ScksAE2w=,tag:vAhSZcXJfV0xml4UDBorxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:cmZ+TXZp90A0LSaMklboM/YmLqMrhlpvzlJEqOoWbRjBnQ4scYe8Q090QnI=,iv:6SRMX6zDHuZCg2Rx03VNS+d6JUeEr7UeL0cfDLPA5aI=,tag:C6o/0humkD2wN0PthFIeNw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:bhWS+KlAjsAmNFb0UeUqIlFGzKamWDTZOz9o7QM7zYupVjEunKMUCbytMbVRDMjuWxGsCJzpvDPjGsn36f0+LRpUnw7U+BfTqdUY0o0F2Bf/CGgeWlcJxg==,iv:W5z6GyoQQnkmhxaGFFBjRFZcnX6s8bvmRFefVq22MwA=,tag:9uC/GOREuo3ewnuwJikLbg==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: foundry
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WkRlUHNESTFLK3g2emZE
            S3llRk9wRjd2Q1h2L294amlIVklTeTRzc0M4Cjd3YjduNWlsbTVaaGVBVTVTWE01
            aDlSSGV3SlZZNXIrUkFjeHFDKzVaK2MKLS0tIHNwOXczUU90ejJkUkRpeDRyajZD
            eEdLM0Z4TDlEM2tQRTN6bXFQaHpKVk0KYHpfYmR02JNTGcCQbI/3xTbdw2GHbXGs
            0mNUrW7H/oA7Jt0oPltDqyyK06ImSye/tfhdBCL/h6NKUjPnIpiXfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:54:38Z"
    mac: ENC[AES256_GCM,data:KzNJ3PrOMaCmy87KM3wCD2Sp+f59njh927CLO3IbLgB7E/TeY3Nfe8y61/CpSSo/taTGgLmYGFqpKp7EvZwddJL9e56adiGeDtlOQFUqRUhxszO1rzD2y2YQPOlOpsQ+0sbdnbKbUZQsMylLx6Vg+0KgHuuuSx6x9OQVmMTnf2s=,iv:Rytgk6tG0oEheIMzzSGSLb/5ipocEeSp151ScksAE2w=,tag:vAhSZcXJfV0xml4UDBorxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:1RUE+rmIVB/viQGPNm0Ten0hTe2QGg7GJzwrtG5nWOBigzLiY86aZUHsQpk=,iv:3fkKmDuae0IRG5DOzh8p0TlZC+ZxjorlzydzEMl7+Bs=,tag:c53J+rp5OM4Fbs51D0PNNA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:IcIJxCCYADr+6Tc4Y8gxkeoC6bFRGgLSrnCqotxEgH3DP2S9RmEJvDM+phOS4z5WDao8OoTuqyYt6DcOXNqxdTLrM3i2Tw1U+pSJL3GeP2w+T02Oqg2+Sw==,iv:USP3QC908WxEF7YToNULL5zGWLJenU4dQcinDVOeWRc=,tag:cZdMztpgQ2R7HJ9/EOJLfw==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: soulmask
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WkRlUHNESTFLK3g2emZE
            S3llRk9wRjd2Q1h2L294amlIVklTeTRzc0M4Cjd3YjduNWlsbTVaaGVBVTVTWE01
            aDlSSGV3SlZZNXIrUkFjeHFDKzVaK2MKLS0tIHNwOXczUU90ejJkUkRpeDRyajZD
            eEdLM0Z4TDlEM2tQRTN6bXFQaHpKVk0KYHpfYmR02JNTGcCQbI/3xTbdw2GHbXGs
            0mNUrW7H/oA7Jt0oPltDqyyK06ImSye/tfhdBCL/h6NKUjPnIpiXfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:54:38Z"
    mac: ENC[AES256_GCM,data:KzNJ3PrOMaCmy87KM3wCD2Sp+f59njh927CLO3IbLgB7E/TeY3Nfe8y61/CpSSo/taTGgLmYGFqpKp7EvZwddJL9e56adiGeDtlOQFUqRUhxszO1rzD2y2YQPOlOpsQ+0sbdnbKbUZQsMylLx6Vg+0KgHuuuSx6x9OQVmMTnf2s=,iv:Rytgk6tG0oEheIMzzSGSLb/5ipocEeSp151ScksAE2w=,tag:vAhSZcXJfV0xml4UDBorxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
