apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:24ch3C3yYGT8MVEoekSb19qObAAjZWlljb05ue4WNKCKcBOUpyck/PCM7Z8=,iv:GyamadjQnIbLZK6Ewi7hU8yrqLoxblZ2a0ybE03PUwM=,tag:PcgSzETrafnf8zrTfZiXlA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:4cDqXporb2hCfFHtk7gu9HmgVChTMxpTVj0heNpMF4AfsEtIC8TGw7mRQdGSaLMro7sauLB3WPZnPK86xZbJVJ395oC/FZm2Znn515GT/V0+lJFfZa3XiQ==,iv:SrqVVnQnG51hNMqYzK3ezTyg6hImM0auib9/ksOBP20=,tag:jGixpBN3mjoJx6TgWxxXdw==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: soulmask
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd2t1YTJZUDFEbkM3Ymdh
            ZmZvTno3bW9zV2RReTlhLzFHUFFxdTA0cUFFCnZmMmhVUXRBNUdnNkcrTUVNOSt6
            ZEliMFBoL0NEbTFRendiNk5SNTd2QzQKLS0tIGtGRHNEM0xkZkN2ZzNRSUJFcndl
            U1o3ZTNsazQwS3FVK0tWTXg5dFgvM2cK8lLr9TbRIIFR9z+arTPSESA6quWMLHLo
            VkPtbTacM+pg85EZxR6X+NBGe+baWx+M66vCgH98eQjjffJK2sJScw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:28:00Z"
    mac: ENC[AES256_GCM,data:eoMMj7HL5Gbp7dFQDffYtgJznJRwey1s9TRdIokqRo6/QrznQ+CHsWXLt4mQdWGj8HtLjRvIJxiRxE82uDxFCKILGt/3UCcYtoxXSTdLgms7PwzGpFlx33DPgwZmz3VRfd6c+MxTUoPsBWr7J/gt+ezffhp1KSkkLjuC8Rr3aig=,iv:mDuehB+1tdiZR+Oa9muq7BKdSXBXIibSIyKbwdOhWBI=,tag:H+AZXzDCI89qHxqskEFtnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:6MkKG2+GW6ELW/dIOVsct/FWnxLwHQXYAw3dNGhE8uhhk8dGlbQEKpw8FqE=,iv:trgmj91ygpXDASD1MyiHsM7boxU1sbHyaNjn8noUiEI=,tag:30DenUQeaJKdVSZuT2LRpQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:I1bMI/4PcjfR1hit5/iM/FcoxiK/vSMmVr8qvipZyJ4+chiGCYkNB3nxqy3SyObJxpOzWX08A70Lj04E61dbITX0WHusBIQoTzCEqKx/MwS07N9k+gEfXQ==,iv:9EAPr2qvkjXMh/vU6bCBo9peUbRoH9O9ukn0JoPPyLo=,tag:HyoqIp52rpc81fHKKK1ZbQ==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: minecraft
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd2t1YTJZUDFEbkM3Ymdh
            ZmZvTno3bW9zV2RReTlhLzFHUFFxdTA0cUFFCnZmMmhVUXRBNUdnNkcrTUVNOSt6
            ZEliMFBoL0NEbTFRendiNk5SNTd2QzQKLS0tIGtGRHNEM0xkZkN2ZzNRSUJFcndl
            U1o3ZTNsazQwS3FVK0tWTXg5dFgvM2cK8lLr9TbRIIFR9z+arTPSESA6quWMLHLo
            VkPtbTacM+pg85EZxR6X+NBGe+baWx+M66vCgH98eQjjffJK2sJScw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:28:00Z"
    mac: ENC[AES256_GCM,data:eoMMj7HL5Gbp7dFQDffYtgJznJRwey1s9TRdIokqRo6/QrznQ+CHsWXLt4mQdWGj8HtLjRvIJxiRxE82uDxFCKILGt/3UCcYtoxXSTdLgms7PwzGpFlx33DPgwZmz3VRfd6c+MxTUoPsBWr7J/gt+ezffhp1KSkkLjuC8Rr3aig=,iv:mDuehB+1tdiZR+Oa9muq7BKdSXBXIibSIyKbwdOhWBI=,tag:H+AZXzDCI89qHxqskEFtnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:TbVHxY42KutDLPKPvOo1Jp4C892kGEZRBA5zE858hJ+OmgZ0RbSfxx5Z0Ik=,iv:oExaeZZz/w/9DKjU2HuJMir4Drgijke3Ss3CsASekLk=,tag:XaeUEI5bLMkuLMmZKaC0MQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:jE3PbaiAXNU+Dmi6Jt6zkYwNVuKPEY0NWfe3r5ptvilGuj8WFZjBe5DjH8hlc1xtIxfHxgTEMMpnPGBExkncXuv9e/lY6sTg7J8oJb4IJYq1rABgOmSJXg==,iv:vU7aCbHzIfHFr+/KW5BCPOQQ0qlDid1/JI6+uSMKAHc=,tag:VUnhSI+g4jY6AAMVaKkvwQ==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: vrising
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd2t1YTJZUDFEbkM3Ymdh
            ZmZvTno3bW9zV2RReTlhLzFHUFFxdTA0cUFFCnZmMmhVUXRBNUdnNkcrTUVNOSt6
            ZEliMFBoL0NEbTFRendiNk5SNTd2QzQKLS0tIGtGRHNEM0xkZkN2ZzNRSUJFcndl
            U1o3ZTNsazQwS3FVK0tWTXg5dFgvM2cK8lLr9TbRIIFR9z+arTPSESA6quWMLHLo
            VkPtbTacM+pg85EZxR6X+NBGe+baWx+M66vCgH98eQjjffJK2sJScw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:28:00Z"
    mac: ENC[AES256_GCM,data:eoMMj7HL5Gbp7dFQDffYtgJznJRwey1s9TRdIokqRo6/QrznQ+CHsWXLt4mQdWGj8HtLjRvIJxiRxE82uDxFCKILGt/3UCcYtoxXSTdLgms7PwzGpFlx33DPgwZmz3VRfd6c+MxTUoPsBWr7J/gt+ezffhp1KSkkLjuC8Rr3aig=,iv:mDuehB+1tdiZR+Oa9muq7BKdSXBXIibSIyKbwdOhWBI=,tag:H+AZXzDCI89qHxqskEFtnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:6SFRclIKtdvMXn9qIw4tb0Sy53lMf3pgZCO5EqnrRu+mf70SS2pUeIX1kHw=,iv:GwsiW4RUMkLdM9QIH2fli6KK6yxVJWER2nN9Bl2LUIg=,tag:Rns+sFaifbf26m+lvtza+w==,type:str]
    secret-access-key: ENC[AES256_GCM,data:qAofuxkiE9jfUJ6Kg34BS9VRf035Ew9Ar+s0ci1YJf4EGEC5tl6LJQqJ0lgIlHP8TLAR6OGagriY82Vu1NedgnCv21Vb1WSgWlmTeGmzWbLGz2mksI4L6A==,iv:/KHWZfAvZo3BDyu6nMKMgn3GTujmYvAlgx4GFqpuTPI=,tag:yxClm7lB37mz+/O/jPC2xw==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: core-keeper
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd2t1YTJZUDFEbkM3Ymdh
            ZmZvTno3bW9zV2RReTlhLzFHUFFxdTA0cUFFCnZmMmhVUXRBNUdnNkcrTUVNOSt6
            ZEliMFBoL0NEbTFRendiNk5SNTd2QzQKLS0tIGtGRHNEM0xkZkN2ZzNRSUJFcndl
            U1o3ZTNsazQwS3FVK0tWTXg5dFgvM2cK8lLr9TbRIIFR9z+arTPSESA6quWMLHLo
            VkPtbTacM+pg85EZxR6X+NBGe+baWx+M66vCgH98eQjjffJK2sJScw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:28:00Z"
    mac: ENC[AES256_GCM,data:eoMMj7HL5Gbp7dFQDffYtgJznJRwey1s9TRdIokqRo6/QrznQ+CHsWXLt4mQdWGj8HtLjRvIJxiRxE82uDxFCKILGt/3UCcYtoxXSTdLgms7PwzGpFlx33DPgwZmz3VRfd6c+MxTUoPsBWr7J/gt+ezffhp1KSkkLjuC8Rr3aig=,iv:mDuehB+1tdiZR+Oa9muq7BKdSXBXIibSIyKbwdOhWBI=,tag:H+AZXzDCI89qHxqskEFtnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:+K3Hf55uIq9WtpDV8UeBwLoymDsUQ7F46KtmxEqCsnoPq9hTEPu1EvlpdNk=,iv:CzhrSho414JhECimldhD/XJ+5BRFIMPwEnPRi0y5SpQ=,tag:JLYsdpOQWYuaJPAZFFge5w==,type:str]
    secret-access-key: ENC[AES256_GCM,data:BRd9JS7bCJGMHOjHdWdj01DS34fnscvEqxl+34nCLOXnUtpvkGgnfQOmJIZKQJBzah1mrmaAlR2xfyqOSvX5Zp/pmx2ZX9nxs+egEj4vwdPrvAvd8HVf4g==,iv:7pePseUUEZke7PfrTO9tMcFcvFQDqUBGkbd7ULXfIxg=,tag:REXGY8d4evU3eWdQlBZc/A==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: foundry
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd2t1YTJZUDFEbkM3Ymdh
            ZmZvTno3bW9zV2RReTlhLzFHUFFxdTA0cUFFCnZmMmhVUXRBNUdnNkcrTUVNOSt6
            ZEliMFBoL0NEbTFRendiNk5SNTd2QzQKLS0tIGtGRHNEM0xkZkN2ZzNRSUJFcndl
            U1o3ZTNsazQwS3FVK0tWTXg5dFgvM2cK8lLr9TbRIIFR9z+arTPSESA6quWMLHLo
            VkPtbTacM+pg85EZxR6X+NBGe+baWx+M66vCgH98eQjjffJK2sJScw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:28:00Z"
    mac: ENC[AES256_GCM,data:eoMMj7HL5Gbp7dFQDffYtgJznJRwey1s9TRdIokqRo6/QrznQ+CHsWXLt4mQdWGj8HtLjRvIJxiRxE82uDxFCKILGt/3UCcYtoxXSTdLgms7PwzGpFlx33DPgwZmz3VRfd6c+MxTUoPsBWr7J/gt+ezffhp1KSkkLjuC8Rr3aig=,iv:mDuehB+1tdiZR+Oa9muq7BKdSXBXIibSIyKbwdOhWBI=,tag:H+AZXzDCI89qHxqskEFtnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
