apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc
    namespace: paperless
type: Opaque
stringData:
    socialaccount-providers: ENC[AES256_GCM,data:qHiSLYFcGKebBsOVjoy136PSOQmBPiNi30J85WmlirtBhwrUXMuAfyJ8n1QYPOPfDbc3aZKMd3r4LEMQ2YGdyb7DfczAUPBclioaggFis1Og7PStj3g+1Fuqj9i9jb1GtMSIRXyFpjiLNzDiuVrmYm1aMDhvVdjzalru5tN8FkcCwDan54e4l515LOp7VvZdFIc7MHGpqrLzJWlE31UFw1YqMH2UVVL3bi1fgw168sKqyduhSQs/XVX+XWeZ0YfflwAfzxNrmE1JELblMxCbARuG7CFURsbZ0O2j5ApiPCTu2LjpVE73HX4B9T4YRct6aF6RkJD9M2P4wQTGtuDPrYvdEPWLEvXNlBprIB/5Qi13xnW7k/WyqVt116+ss5Da,iv:7aJDBuQsSDfLDMJms7nbFIs80oPS8IU5l8gdiGow6os=,tag:Z72M5LaYTcmZ0suwnthFMQ==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNG0xbVUxMmNlQzBOSDJN
            TE5OR01hZUs0dCtVUmhuU0Uvc0JSWXFobTNFCmNXUmZtcWY1d1ZDWEQvLzBQWTFi
            c2RrUE4vL056ak1YQ1NWTVhRbGhzaXMKLS0tIDlVcmdnNzNjRGtuUmNkdUttcmpm
            Wm5XTS9qdnpHSXM1ZXJyR1RPNkJYK1UKJQIqSvKd94aL9WI5VLYcu/HQ5mUNO1RI
            HhpWIGJL+6wjKzgwmjI21c3fVqYAgHtjDeB2T3UrI8zfQNOAVyZzZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T18:55:50Z"
    mac: ENC[AES256_GCM,data:nhlh/ntz8Cun0164C9U121oXCd6I+TCdRlMwylyQomLYlnoZni/MbqIxz257d+bJkYNEKtO0/FxO3WjEcr8q48LpDNGywYRrKMwISAY0qmMlyzNpqZE4QDvjNFMMBkZ9KZLvWV925Qa1kGxu773TbUKFq+JkjG0ESHEU8Cy47mI=,iv:tBIvwHq7Qi7lX5iXgH0rKdebRy64H/+AhYhlSZig1T4=,tag:iXyRkCw//KXiDYTOsNOJOw==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
