apiVersion: v1
kind: Secret
metadata:
    name: paperless-db
    namespace: paperless
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:8WVqrKG1+CkEd7QhHfar0jKAWy5enAxMliUVwN5U0EWvE5wU3ZaqDGq2ycs=,iv:5zkH8F+IS5S1tToUEErleMfbh7GHSwHdHzWS7ysxSFA=,tag:GJR7slae5AZ5h8dnPCl5Rw==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTW5KLzQ4SkNRaC81aWd6
            MFpVN2dBWExZemdja2hadmpUK1hvQzlwUHhvCnlmUGtCYUZIakp4dFpNbHNOdG1o
            NFlPVVBwSi9uWTh3RGxNUGY3dGFGamsKLS0tIFViR2dwd0hOYVh1WXJpcHdWMnll
            LzFTeTNFU2gvZjAwSzlzSjRreUZVZUkKzfZ+K/PxUGhs9Jg7HfSNuac79YEVbSPl
            G7vs72NJhi+YPffLuL1Yk5u09Mj2DiHusCXXsD3ekwfOqYTH/y4YXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T00:53:59Z"
    mac: ENC[AES256_GCM,data:yitDOiQgM3fZTe5eFlxlgcVCOYJWlBbqa7nBbxiTY6s7lO0GSzk3iNXjriuVYKGyuowkzAE/PACWkZiOSryy6l3McUKZj7c1f+F+kbPIIv6ubdtImNx1XR+M0+uRVdu4MnvYfWr0bC/LaJspszuixkF9Zri46cnTvkFZqKXVQEo=,iv:wNrinCPoqX239c4XbYf8J1vmfi7OOWAclXSbjfeZXxQ=,tag:N3mpyhZdnNoaFsRyNYAGHA==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
