apiVersion: v1
kind: Secret
metadata:
    name: r2-credentials
    namespace: booklore
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:R8pd579I1tQctYKTo/nxKx5OuPliFXdy39QYiXScLSQ=,iv:ZmV9l+eEoyX+cJlgSaZWUZEQ7QaGVg5zO4cDQxG8eQY=,tag:9dEo9OZRYX/NlrKgidfjmg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:1RSLIWilZ+4rFLzj+ZwLsZlJ7d/O4/Ri1n0sLC/I9IWFO7HR3bdkghB8ukthS/jSO0yr3xZlwxvZ+/++BmBuvg==,iv:RtGI0kfq7Qib6hpiLoB2eO7xCttxxHQItZEIwP1BGMc=,tag:2UUkZ1J+d7vYfm9F9h1SYA==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT0RXb1VKSGJSaklpdk56
            NFQzblhGb3FvNmozVWtMa0pPUzVzNkFJcVVvCjBabEZJRHA4VzFmVmEzTWh2OEFN
            Ymg3dlJBYWFoSWlEVDY4WlhSWUd1OTgKLS0tIEZLMW1kMUZ2TFA3S3h0czNLcUZu
            QVJBbFVzLytQL1dBNE1GZWlTUXBXUUkKVchTiXAG6pAtcOjFKPBau+LGBW6SOPZQ
            twCpM9eXBZvQc14dEuFjJu52edXhCI+0jDkj6mQ0CxipFhQTUa/ovw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T20:19:32Z"
    mac: ENC[AES256_GCM,data:597Ytf+bmxA2tQVJ8FNGGyiIu78HJFlD8zyexuljlDND2uc83jLWQTZyjds90zxXr05moVXRvc6T9wlgwi8hKc+7U0uojqX7Uir0lBUtLjBvThZvp2tXa+oRlb/MWTHjC0zTo/oUwYo8vmaDAwpYoCtJe18W4vIJaDNhV2Z2gz0=,iv:c0hGmvs2jDADkzmEvjCJFa66dygtzeuqpeGXYqfUEX0=,tag:udLMRKRwQLBD/JUXxDXb4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
