apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ljTnaPKQNjILEOMNXKuzEgJZ96v47amqcRkp9WXe7VtmZjHc/nnxIJvCSY3xA5XO0SlyR1DxCe1jOkDhRkljoYPxPhTrNB3fvz8JUp53kNILADAhB42qE8K4+9J21Ia69jhBD28KNuYYTnoDDqtM+CXXXLydpxWnxvkREVGAERGOuxOPMuop7YGcSgdvSyE5Lu27GY3IMF0CCLU75S0VJZGJyDRQLy5J/rKoq1X4kLof+yur30b1NQ4Z4p7bEYFxAadUfGrOM/pwH8/aNuXKk1wrJZgoSgieXlUmRFiDqbOP2+3N80wPG3mczN8=,iv:g0bTsTAR/qr4M1dqlDvwa19QpRlySwKwkYYhaNvsFfY=,tag:x1wXMymKL2qGFCbVnMw7SA==,type:str]
kind: Secret
metadata:
    name: cf-tunnel-secret
    namespace: cloudflared
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJS3BQUEp6NllwN2o3bXBt
            VGdWaklQRnVNNUp3NmJ2MFBReWZ1V2dYeWlzCjdBcVA3ZDJ2S2lWWnNCaDk3UGhn
            cnU4WUZCNkluOWdiRjNZT3JvN1ovSzQKLS0tIGJjRlZaSy9Id1h6R2dTaEc2b3lQ
            Nmk5Y3NIZ0h0Q0plYTVOYi83NFlsTFEKefGIlawd4IvoqhqPOSERG+PAS8hfm61C
            jkKob0CXWYt86isPKAFWhTKULBIghuLH+bc66NH0lePoU8l7gFoVtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T01:35:31Z"
    mac: ENC[AES256_GCM,data:61o5Dn3tX7HeAvS8JMf2tA9l/aq7VD2OrdXYRfOtGNqm2CpkLJSol7iiCprVrXXvo3GFWQAXsU0LaNEuwrP0kiwGeV5jTGLkVV2PCNANrVujWbS6vwyAlJLnAMjshTKc9tuF8JiCmVf5kf4V0YikpxDpw30/KlGoY8NipkmEK3Y=,iv:+rfOlpbsN9AV6aHR8GVsRQUtU0nbIq04CW4OwcJDTh4=,tag:JkZ5WFZaI2qbEuRUigHaAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
