---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - booklore-r2-credentials.yaml
  - booklore-booklore-db.yaml
  - cloudflared-cf-tunnel-secret.yaml
  - vpn-wg-easy-password.yaml
  - kube-system-hcloud.yaml
  - monitoring-grafana-admin.yaml
  - vpn-xray-reality-secrets.yaml
  - alertmanager-telegram.yaml
  - pocket-id.yaml
