apiVersion: v1
kind: Secret
metadata:
    name: dune-awakening
    namespace: dune-awakening
type: Opaque
stringData:
    DUNE_FLS_TOKEN: ENC[AES256_GCM,data:TGNlRWkuZprUtjDK6UBYqm9M5+lVHnhGqflh/CXyaWqIIDiR+0QhXvQcquZfveiCkj1xyf2FWEil2BUiB09NVt9FI6CCWW8c7Ka2FW1sUw5mtPfcPWosezmn8USBUz+ekcNxni1R5qByonNESi2SuzkCJadoqoOdCY4lCUBIr/dBXKLi8VL7GRvy9n167K1Ver9p4MPbUHR+ivIbQ/HMYta9rSuJpPRLjBLtAhBMX3XaEwXv91jpIW/J7uNntajUp5eqsxKn4e8HS+AmZpbT6iHECkSlzxEZ9w1eze3SsAtqymdJZdB3ZUbBq/Sp6lBphJAmSAJzHSneOUTiUNa/vivp3aTjY/XzE5sf62TxaNNBOBp+kwkkFOqL1sFRTvyTEWvhAQxcOydHxOzG/TKHyKNhGnGggG8UwDNy11h3Sqr7q9FLMllKj6Vsu0I090MkQgOWFYrOcAa2OeFL7e/G9Q==,iv:U35WxHqlyVZjI1OEw64Z5/yHn8mYgbKLrqj0Q/+bL+U=,tag:UmVYMX9wgj4eUlvnzx+ksA==,type:str]
    DUNE_DB_PASSWORD: ENC[AES256_GCM,data:dE/fKDfv9PWfwVcO27qCLm92/ETzEN9U,iv:/JzS6jKcRo7Y5V6Ti5AQKASHTp2QkntovRAr5DtqABk=,tag:RuLO6n9gkD0Ft0inKY1nYw==,type:str]
    DUNE_DB_SUPER_PASSWORD: ENC[AES256_GCM,data:p8voNuz0q7xYEZa3yCUWKbKKZ3gzIUeR,iv:t+xbpHHhROVsvSS8b6IWI2kppxrx30UwN4l4uQWlhtc=,tag:12xtESP1h2DHO7J4pBDx5Q==,type:str]
    DUNE_SERVER_PASSWORD: ENC[AES256_GCM,data:+ma5No4Dw+0=,iv:cQgG/pEOqPv8pa38bTpJwbWY6LJ4bl3SjK49Iz6CKTI=,tag:SYbwcRI7WhpqU1chZnt3bQ==,type:str]
    DUNE_RMQ_SECRET: ENC[AES256_GCM,data:vlf2BOVTakoI09FrU/fKTJIeu2UJuVVXLB/oCrUopdFTSH2Hqyvmh1Q+aUzWmrY9nYFrWEJLV28HdbJM4yDlnxQOBTX5l4Nc+2+QpzkHaFfdIr9lcQnCOg==,iv:CdKIOJ65l3ZG5vpyGinC+2atm8H/55bc7Tx8m+noaCc=,tag:PYTx55Ksem6KPo+ifDxOew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbm5nRU1LQnk5UzZac3ND
            VXFBa29zTVMvTFZ4cE9XOGd0a2RlUXBzeVU4CkhLYUUwdVFpUGVCVmFyVWxhSTZT
            ZU84U2kxSEIrN1VJek1vcFFaVWVya0UKLS0tIEY2NHhGS2F2aCtHZCtSc01OTnZi
            RXQ4S0ZDZXhFczFkTXhrYmFJQjdxaGsKcpNA4Y1Ab/4krMHE5PaeWmljk5hAdg3N
            zSWY7iRw8cYb5IKy6HzlVrWqraGTdQzQKWELe5ik8QOp64EGHoVoXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
    encrypted_regex: ^(data|stringData|secure)$
    lastmodified: "2026-09-27T11:57:58Z"
    mac: ENC[AES256_GCM,data:VaGEEYO1RztMF7NyqOeaJWiFH+fsFYYJ5p1SFJp5WyaPtRD0OVueA21XbA1S4HYQDptgMSOJs+yutJui7GjL+f4D0k0lTL/XDEvJfM+tVGhMhvK/uBQ5LKnaUEO7QRky07d9fcdAH5qTbmvACtjfpBJL5Kc6Kpc88IK6EyJy68A=,iv:Xf7oFPiLYeEbfd8agoXyybRg8yTydA2HB2H2EV7/mDg=,tag:1BPnFjKOntb4u+0UkJq3iA==,type:str]
    version: 3.13.3
