---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - core-keeper.yaml
  # - enshrouded.yaml
  # - foundry.yaml
  # - minecraft.yaml
  # - palworld.yaml
  # - satisfactory.yaml
  # - valheim.yaml
