apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-vless
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xray-vless
  template:
    metadata:
      labels:
        app: xray-vless
    spec:
      containers:
      - name: xray
        resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 512Mi
        image: teddysun/xray:latest
        ports:
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/xray
      volumes:
      - name: config
        configMap:
          name: xray-config
