---
apiVersion: v1
kind: Service
metadata:
  name: sleepy-notify-bot
  namespace: telegram
spec:
  type: NodePort
  selector:
    app: sleepy-notify-bot
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080