---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: dune-awakening
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    includedNamespaces: ["funcom-seabass-sh-47951649e36d38d0-zagrib"]
    storageLocation: r2
    ttl: 336h0m0s
    defaultVolumesToFsBackup: true
