apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - namespace.yaml
  - pvc.yaml
  - paperless-db-secret.yaml
  - paperless-oidc-secret.yaml
  - paperless-config.yaml
  - postgres.yaml
  - redis.yaml
  - tika.yaml
  - gotenberg.yaml
  - service.yaml
  - deployment.yaml
