apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc
    namespace: paperless
type: Opaque
stringData:
    socialaccount-providers: ENC[AES256_GCM,data:isEe67l6MjMjVoBj470DV3iVUrGuyl9UUjZULyrdeXV5nmLudi4er56kYq9dSPlxctKPk3Rovdq6MTafWT+tk6nIjEC59tDxiuh/vW2y4cQWWGMTmNrRRtgGQhX9H6q+DTCcc6kmCSCKCPVAzXMrSmRJLwLZmwvsyr1XDQAS32P21KKybIBcdgV7WZjd81Z+UxTAeWiRT/rBlgBgyD8r8mumuSD3uaTToepcRvG42GKEftejjDbg6o9CJrUcGYrZAaMR8lFD6QCGqAlmS9uLgpUglVblpjY8uJWx6BgAxhTj9b2HDiCAQwYR/HszyFI4tgYNcUxhWPZBTZDWM/PsasbD0NfrXbmMePBrarDn4G5omwrthXaJCUv9yhY=,iv:1jHLaLYBUKPFWsufYAvXZv+N4Q5TuhOJsWvIBKIJToI=,tag:VyoPyjh1ddUTlR96axLsZg==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNG0xbVUxMmNlQzBOSDJN
            TE5OR01hZUs0dCtVUmhuU0Uvc0JSWXFobTNFCmNXUmZtcWY1d1ZDWEQvLzBQWTFi
            c2RrUE4vL056ak1YQ1NWTVhRbGhzaXMKLS0tIDlVcmdnNzNjRGtuUmNkdUttcmpm
            Wm5XTS9qdnpHSXM1ZXJyR1RPNkJYK1UKJQIqSvKd94aL9WI5VLYcu/HQ5mUNO1RI
            HhpWIGJL+6wjKzgwmjI21c3fVqYAgHtjDeB2T3UrI8zfQNOAVyZzZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T00:54:15Z"
    mac: ENC[AES256_GCM,data:rPgd1d0LrsTCx90Ef3f2yWqRvYITwdMaXv7+VzA4f6otj9RpEmD7ewfFkHD+DpsClhPi6NeWNCbNylk93jRB4l9F7zZ4KAxwphlA7HcW4x3FAvDBnf0gzNtKFj9svuwO8x3lK/vR5FcnegfiA6JLmXQApEcBga0+nfLRwxYnEOo=,iv:xO7rDYxRj+sEDewYB9ywl5bqFeNdWmTuPYHpaJjEcng=,tag:UjeoHkPl8yl+vtmCordmyQ==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
