---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enshrouded-cm
  namespace: enshrouded
data:
  SERVER_NAME: "fabler"
  SERVER_ROLE_0_NAME: "Admin"
  SERVER_ROLE_0_CAN_KICK_BAN: "true"
  SERVER_ROLE_0_CAN_ACCESS_INVENTORIES: "true"
  SERVER_ROLE_0_CAN_EDIT_BASE: "true"
  SERVER_ROLE_0_CAN_EXTEND_BASE: "true"
  SERVER_ENABLE_TEXT_CHAT: "true"
  SERVER_SLOT_COUNT: "4"
  SERVER_GS_PRESET: "Custom"
  SERVER_GS_PLAYER_BODY_HEAT_FACTOR: "2"
  SERVER_GS_PLAYER_HEALTH_FACTOR: "3"
  SERVER_GS_PLAYER_STAMINA_FACTOR: "3"
  SERVER_GS_PLAYER_MANA_FACTOR: "3"
  SERVER_GS_ENABLE_DURABILITY: "false"
  SERVER_GS_ENABLE_STARVING_DEBUFF: "false"
  SERVER_GS_FOOD_BUFF_DURATION_FACTOR: "2"
  SERVER_GS_SHROUD_TIME_FACTOR: "2"
  SERVER_GS_RANDOM_SPAWNER_AMOUNT: "Many"
  SERVER_GS_MINING_DAMAGE_FACTOR: "2"
  SERVER_GS_PLANT_GROWTH_SPEED_FACTOR: "2"
  SERVER_GS_RESOURCE_DROP_STACK_AMOUNT_FACTOR: "2"
  SERVER_GS_FACTORY_PRODUCTION_SPEED_FACTOR: "2"
  SERVER_GS_PERK_UPGRADE_RECYCLING_FACTOR: "1"
  SERVER_GS_EXPERIENCE_COMBAT_FACTOR: "2"
  SERVER_GS_EXPERIENCE_MINING_FACTOR: "2"
  SERVER_GS_EXPERIENCE_EXPLORATION_QUESTS_FACTOR: "2"
  SERVER_GS_TAMING_STARTLE_REPERCUSSION: "KeepProgress"
  SERVER_GS_TOMBSTONE_MODE: "NoTombstone"
  SERVER_GS_ENEMY_DAMAGE_FACTOR: "0.5"
  SERVER_GS_ENEMY_HEALTH_FACTOR: "0.5"
  SERVER_GS_ENEMY_STAMINA_FACTOR: "1"
  SERVER_GS_ENEMY_PERCEPTION_RANGE_FACTOR: "0.5"
  SERVER_GS_BOSS_DAMAGE_FACTOR: "0.5"
  SERVER_GS_BOSS_HEALTH_FACTOR: "0.5"
  UPDATE_CRON: "*/30 * * * *"
  PUID: "4711"
  PGID: "4711"

