---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enshrouded
  name: enshrouded
  namespace: enshrouded
spec:
  type: NodePort
  ports:
    - name: server
      port: 15637
      protocol: UDP
      targetPort: 15637
      nodePort: 30637
  selector:
    app: enshrouded