apiVersion: v1
kind: Secret
metadata:
    name: git-sync-pat
    namespace: monitoring
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:gw0q9XZ0+Y56olVPbfpA4FIC1euCYfsDZVZxNXFDGlrObd9xTosKV+OTb9BenfgjfFQmOH3ki5jfCIHyHgaw0tsDge+8qT8nAdWtGNsvLDQbxCEqpk8IjWGCQcQh,iv:4XluBXC1akcJ3Ixo1vvp51hNKnU3CRNvRNCH9uoTCLM=,tag:b0Ulf6BSi6zeIlO8oeowlQ==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Tnl0bC9pUXk1bjM2eWFU
            RGRFVk9kdUYzd2VMRHpUcWtZdkgwRm5NNGwwCmsweDdsZUpwcUFkaktyeW1WZ0Ew
            QkxQWE5scEc5MXdpdDN1elg2WGl4L0EKLS0tIE5mS2FkajcyeTlRdjRxZXEvbWFt
            NFNVWEQ3QmhOOFY1anRYMGdZWmdqMEEKHnDdxo19G2l3Y7JyQiGAPqfFc5P5sCjw
            BvztI8BtODTo5kyEGY/KSxRhezmyA530E7A9qeW8xN4j/O/9NWMgDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:07:10Z"
    mac: ENC[AES256_GCM,data:8Mg0m1CU1uKAAq/9iq5KdGFu1WdBy78WrWy43cYXwr3rjDqj7oi3ZVMzHfkGpVAKkjnmmcGrFS6j3ewEha3S+ZeXu3xQWK5x9TjVuwcwAWUgb4kzl+/e1vp1AtuUVoPaXKNCSpBH8aLzUmu1/QZvUegnpDnJbxTaOqsqS7F/8QY=,iv:QQFo5Z5oh4VquKV5ZiDOC4/r86Gh35H6YwABB8CAlCc=,tag:amx9tiM83WnYGMom9s/wpQ==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
