apiVersion: v1
kind: Secret
metadata:
    name: telegram-credentials
    namespace: monitoring
type: Opaque
data:
    bot_token: ENC[AES256_GCM,data:LODjI4uWgIRdd79TBSTS4zZpwQq0oxsCRKSyThZBIGrr12TV40/9e9rx/ApI1+zQBEO74AKCRhGlWqorqBvCFw==,iv:CZlPr7qYpuJn1hYHFG/O5C4gSZghRbmK5FF9RFOWYfA=,tag:NbiTNd2BJxz077iEYds4Hg==,type:str]
    chat_id: ENC[AES256_GCM,data:AWEyhMiVxPM+8gF5,iv:8JyGUWxNsS+VfVstP0GhpQW7zKc4jpu+ieJ/xLfDQ18=,tag:iOSTnjJMCYNN0Xg1osjMeA==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSWNiSGQ0SEpqREhXSkJ6
            alp0MEFrTGV3cmNORFNaaUVmM3Q5djdVdzNFCmljWnlWbjdkWVUyUDZNLzAzNERS
            Z2xzYkdySThPUlpWLzhPNTFBVFg3SnMKLS0tIFRRbmxob3ZDbjN5dkswWW55azlS
            Q1RXNmpWSUhkTGZzUWYyOHJybVByaTQKXU0bwTaUqi2NSQ+pQDVyHs4lVx7ybxw+
            vojwDLiuBf4nyjEq7EGrkVdInCOuhMghCeM78COQxZkfPtxYv69siQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T22:46:24Z"
    mac: ENC[AES256_GCM,data:WEU29/HyqKLihRmpH8QbEhHUy863am+Ks8EXMIluDbQwbIDCnSIsYcZIPTcXeJdfXLXECVAs8Xy/VlXCm755e6Oh5zrAJCNaslGg61Kndt/FQAAZWjcm7aV2OHf0ULFPV9ae8P9GTeOg0P4SaOwJRQ8TD69d9BKvurtthlFjZic=,iv:oVfE860GwtwpktF5G6zU/LIBgxdjwBE+wOub0nCSV/8=,tag:VHxiulLjNkoY/Zqlr+UEQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
