apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-vaultwarden
    namespace: vault
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:mwP8o1etv+uJWfy+dqL8McOqxJtWNglRbAaxfLYqihwB8CyQ,iv:er3KnZO89/+xBuGcA/bqVaHa0bmgi2LgWSl1Wb2hPM4=,tag:rpz9fXB3p7DuKxfuYSA0Gg==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:1C+82TYPzRr2zxqdPZ/mCuoidPYAmHBzKIq+MkfzBVw=,iv:qPnZEMe/NzbapxZdeWYVUqlm6Iwqjya8nV0CpBCNjtk=,tag:jaUai1hxAyxTwDpoo4PM5w==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:nfBnybUydBVVLHD5M/VSDEmKh0ZR10NW6inGfypbI8Nlm3BGC025Hc2DY/U=,iv:h3/OuPq92i4y2BjiOe+V+o0xNuYh+0l3rWY/PaTdU3U=,tag:tk5sGyk48DfxdqsKbzksLQ==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWkZleHExVm5wWlhsT0Rj
            bENKZUNlb2dwMXJzc002YTVueUQ5aDhNNEJzCk5RNk9mNzIrNlNGcTFRTHI4ZGEx
            eWlWa2NvUElZQXVkeXMyc2U5SDZkZlkKLS0tIGhhUmdMMVk2bHgwRmp0Mk16cDQ0
            NWdFQllFNVB1VWMrb1ZDSk1maHJqRVUKt5OJNIEGq7K/hFfkoygdEWcuSwtjraG2
            skVXSgOk6YP+m/aP0uD+5JsOBNwYQCVBozy8z1DNjZ3v4nIf9Lc1eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T13:55:42Z"
    mac: ENC[AES256_GCM,data:6hSOLET9LTeRhFrlyx5LNI21C229pBrLbNb8/RYNj0PVOlT4LpWdCYRVrzCCPFmDYkCV/gQU9DgXfttgxQDQKphk1lRZYhiwqLEUc5Tr/Nb683SYQkW/NrDa/hLeGohNqRudjiOfdp8T4rtRDpfXdbJ64ERQWENGTimmwCASUUo=,iv:67MWQilNdqQuBIq4in7ReH056iiyrikC7hIum9BHrwI=,tag:OLZ76njOZQ3E4pZcbvJlVQ==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
