apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-oidc
    namespace: vault
type: Opaque
stringData:
    SSO_CLIENT_ID: ENC[AES256_GCM,data:6d/Ay0S24ngK9DUVUT3BS+ZWWmq6skP43Qn51TlPn30gP8up,iv:UAW7PuZIp8V/RXSem/ztJEhpvlLMv6KG1fHrYqogWoI=,tag:qMPL+dZMKdA4baIBjCosjA==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:ieujinHYtVn74g5ajNlVdwDHyE9/cncnfGv6bV0EmKk=,iv:ejjQwaOgOWglapE6vdKaXqxitx1JSi+cHmvforPLsv4=,tag:819ZeDhnCZM3T2ko3mwKkw==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cm5raFZTdlVOOEFkb0d1
            dVhqa1EyREE5Rm8xTWpiYkU1dEc2YWlGRkFnCi9BTnFQNEFjbERTWUZtRUpnLy9a
            OXhLeXB2Q05HZk42R09lSUx5SHJHUzQKLS0tIE84dWJNYmhTMkR3TnAzcU5nMVdG
            RCtBQTNma2d5UXhoSnZNcHRSNXpCYW8KFB03Vf6W8TbvSYhYIct05h0ceNv5LjpO
            GxLrSOZi48AiLZCbyKPnq8Oa5etI1MTkQ5coYD9T9XneAcdipW8L8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T13:55:28Z"
    mac: ENC[AES256_GCM,data:99HgsqytpIsLpmVkl+KV4GkSjxjB94QmxmLBpj7AH2yXMYFhJxAheRCKyvTTsd39TV5f850EVKIAPqyPxMmjMDxLnlht8vBlw4TsW+NDzCyu9EdY8sc45+0yd8dRKqFcUEIvt0YNqhO5dwVdyAFt+padyL0jIiRx8YHgn9OPmFU=,iv:9seU5HsKdg5A/OY9vqxWQwuCTf6A3LbAwG9xVCPwlJE=,tag:TQuR219jwEl1QfRqgMG8tA==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
