---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - booklore-db-secret.yaml
  - booklore-r2-credentials-secret.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - mariadb
  - backup-cronjob.yaml
