---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-booklore-books
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hcloud-volumes
  csi:
    driver: csi.hetzner.cloud
    volumeHandle: "105564686"
    fsType: ext4
  claimRef:
    namespace: booklore
    name: booklore-books
