apiVersion: v1
data:
    modioApiKey: ENC[AES256_GCM,data:5rqo90T3Hq49e/8lm74uOKJnNh/pExX+VF2IFyrxOMRDcrB/3LgCzxNYlUI=,iv:BK7/K0phR0eLpY+au6meTMhKWE9h9dGst6xUP/3UV7g=,tag:OmZW4dL/cQIlgGKrVo5qOA==,type:str]
    modioApiUrl: ENC[AES256_GCM,data:eumUyX1ReIwPMYcKL6d6gYJikBZ6NaaFXhpzFbvsBIouIj4Gukvh7OAIDKk=,iv:vfIbTSE2JRbufDaWLG3KW7vrZGqG7p9U4d0xuCX6uAA=,tag:Dy2npfRrrmnjC2c7zE5Cig==,type:str]
    serverPassword: ENC[AES256_GCM,data:eVqOIfzBHLX4PmSK,iv:pcl3P8HfYQPpG0OYVfAPJbIWg4xZJDIu2LQmrgiod6c=,tag:zVXMYp/ht2Yxxq7AXL68EQ==,type:str]
kind: Secret
metadata:
    name: core-keeper-secrets
    namespace: core-keeper
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdkR2UXh5Y3BLZG9Rcmty
            OEhyb3ErK1FBT2xIMWFoSmRCelJzcmN3M3g4CjZZUUdHUjJUY3FEVjdEV0FnSWNO
            UnRnZDl3UDBkNDM5djM4ZWlRLzdSQzAKLS0tIFMwb1hNaGN0SGZlVWtMRVN6aE5u
            ZThvRnJQaUI1NnhBdE0yYUZyb2dyL28KeHlLAsigMuRvJ00AKYhPAzG+nh3BgAOL
            VaubcA5Z/LxVqHJ1jqOqJ9pfMQU2nd9oHioqx52HdOHvHEAVwdMfUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:15:28Z"
    mac: ENC[AES256_GCM,data:zX7ZcpzRF1jZWL39CWRed39XxxWDCKWw5I7NWNukTqCWyMcR0vlTam5xHudeb10L5GOpJ7LRumE8iXNM6A1mJo9cB0dMZozBBddcoiCezlJeS1/qicCliHuZU4iIQ5yot5Dsw1HdQ/hNuCG6WS/sQR7Ve3PpmwPwVub3pOMw66Y=,iv:K9QRMqbq076YN3TRSzHUGb23ZJdTShyRq/NWgwwQ7L0=,tag:jKkzV/5h+Pw1+tvIrTFvDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
