apiVersion: v1
data:
    serverPassword: ENC[AES256_GCM,data:yofzVqmT8bqTGulw,iv:EEGmiZ5so0/rsg0ZI4RcacUzqFXPPPh1k9u2VO8hGxs=,tag:S70j70luPf+Agvx79SkFCA==,type:str]
kind: Secret
metadata:
    name: foundry-secrets
    namespace: foundry
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbnZONXhjVWlTNkdKRXhO
            NmRxcEdGa1k2bEhCNWFySUNRQnhqMkFzL1VnCnpqZS9WOFBlS0xOQ2d4OW5ZSDVZ
            cXlUcnRNWDlCcmZoSEY1NTMzOGNkbzgKLS0tIElWUjdrVHNIVUlJV09Hd0VMcjZw
            UytVQXl2bTU2SGRPYWxWVGU2MGRtL1EKIHa18FTKWHQISqt6kZyDGxa/lF7SzFgJ
            r4TdcGEiBl5kbJC3tcgIntr/uxJLlysa7DhBfViE+OwVy6QCSZ1Paw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:15:28Z"
    mac: ENC[AES256_GCM,data:mnk3E/Fbq6K2+pWmFKnvGgs7yvL0gb/78rGoIplWxEcp/ljctIADszWIru9HWgucrhn7PJeh3KR/yFVMdn7Qc0Qt2nNDCG+SF7EYMxGl/1gLB0LIokojwI58gJiQK3DMWtUHwk/thDaygBgafyGoZxqBAIOqX6r3vSJ8zaN0hjs=,iv:HWChekbTLsH+zVaDHB55s2N1utVSzQSzPYGovHjyVxU=,tag:pWhHqjmXHBrHaQS6xZQeOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
