apiVersion: v1
data:
    network: ENC[AES256_GCM,data:T4ptrAkR+uHYFn6w,iv:UtJVnpH4Q/3A+EdCwnkJNzTtZIp2+DAvSkzwl5vn0QI=,tag:SwI14VxDLGtqs456Kc248Q==,type:str]
    token: ENC[AES256_GCM,data:KSAYOY1xvorfqqBawL+rY7Y3tRjn0908Lg2WVIF0esd5P16IfAblKBX1+bj/2UxwmQDuu8+gWf/akkk8v+b8lAZP6aNVcEw72RReSrj8KfjPWD9ZB5OcIQ==,iv:RThZ746RAp+fygkHJ+5vFm6ronnpGftIZiPszdGAbyo=,tag:UeHDYsg8zTRYnDrDpg0CJg==,type:str]
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUHBlTnJ3d2dxYkR3V2gv
            ZHlXc2ZjL0JieHVQT0lDb213TlZOZDZvT0NnClVGd1VkNGFVTHhQc1d0dFdkQzBW
            Z2hQMTFDS3E5QjgxdkVtN1FqUDhmWGcKLS0tIGtPelhtRWtKcVQ2czFEV3hBVitK
            VkFlVmkwM0dPWWVSOGQxejFCRFp2Sk0KE+sX9sOBZlyXRgQSczoQoMxxk7ccxV6u
            xYTiUneWXrgXln5kRUS6Zl0mY4HKmlPILSOKvDZZPIDmDhZIaKoXBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:14:45Z"
    mac: ENC[AES256_GCM,data:rXefVszQNErd0UDw3lWn2o19ewpYaOVMgZgxxleB+b1Fal6NclAGhhAHfuyZdLyDw8b/Zg514M4LlifTy+rdzacB2giCTwNoot5q9pgGRCYmKlKDn4F8xv1dGGJUKOhWf8zUyZx2fLd2OnHMIo/trvonNKBfATN8J5WvTsrXoVo=,iv:BsYLDmmr0Z0vo0/uItlVlLFdGxsr5lGAgRCWcZWkipQ=,tag:ZK5mWkeSENurRhcVHnjO9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
