apiVersion: v1
data:
    serverPassword: ENC[AES256_GCM,data:hm4/hfyudJqt6LEj,iv:cOHGF/wDTeyjGfbSIX25F8dU0y5s4opR355wjzaJsnA=,tag:iMviD1GwoUrXt4iGKwVrNg==,type:str]
kind: Secret
metadata:
    name: foundry-secrets
    namespace: foundry
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRkFyQW5SZEN5MERsTzBL
            Z2R4MEdxOHZRZEpBM0lwWGdhV3V0Z0ZqcnpVCkt5RXpiYVFvaGtUazBhNUkvUzF2
            QUdHNzJ5UXpjMFhENkY5QnI0VVN6MjgKLS0tIHErZEJEbmFpNXptUmtFWHBpd2Ex
            b0VSUXh4NGFRTDFJUi9yd0lIdnVPOVUKVZMXMe+R73wqalrmuDoD2QqfaMBxbhkq
            ss0814HGHjxTXANVX81gmz2Hd267ubI53NeuG+HE54tCiRW0pL9NEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T16:28:00Z"
    mac: ENC[AES256_GCM,data:hkNwVpbAkdYzyGARuAQGxkxOgKyQN8GDU8GKJpAVwMiTap5yZdz606zfUMFv1NcwdohuPNDVnUUs2ii6RL0gRjhNCfR1WwQQ/r/NoANQMg341vj2tpglIsuRGn4hwReJPdc9FJPHV/TU0mIFg6ABKkXuGSC/UMb1ZDxqMjEypaU=,iv:FgKaO7YFbv5xlewoTFa/2dzpZ+++iZBzhfdULhSiOHw=,tag:SU6TIfvJ0+6QbwBRHTA88g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
