apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:OSEIej/vwKHwM3A9jSStY+uvCsOT8pJxYC2CqAzDyCgoiXlGdDWIK8nKKpg=,iv:I6BR2brkGdNN/sCXEJp7idDuPFVmB2syX+TWFfcl7Qg=,tag:iFAqzOF64x/w8yRIhzQToA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:Q2Q/prbqU4M54urgSwF9RBIwQgii+Dcb2o9jx+YkyxRiuJWLmRRe7FiBlQBLd9upbCwJHTYve9/TjSbn8gYCUTohkVHvmMoaLlpZhzCfiiR50b2ae4TUmQ==,iv:kZD9quqhbf8G2G9JhvD9wZMd8/l1SlqPdAow4OUeTgw=,tag:l0ojwnkZU/ndx/ZANvKRdQ==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: booklore
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK1Z1eFRjbWNxRVhIZnNj
            elRRZGVNT21CR3ZBRTJ1ZEY3RXA0akxURXhRCkFybVVSSWsydno1VTR0b1lMdlJ0
            R2t0TWlOdGZHemQ3K0RwZS92d1U4c3MKLS0tIFhxbUd1by9RS2ZtKzdhR1RZL29l
            cGt4bk4wU3dJVW51VENTb3kzOC8rMWcKXG22StESEke6Wf19mo8Tbc9Nt63MPQRi
            v13XQ/iM2WAjMOmeC248OwltXjgkr6cfg2eDKjoRzzwusVkK1dJG4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:54:38Z"
    mac: ENC[AES256_GCM,data:eEhqxW3mAlGLsmZ17p1x24qILjuXRdPSK3i6niIVQvUmfA77pdFMm2bRQtCcpjMYr0p9iVZtHptFpNPxpwcgEdZvKQGbTOiJ0pQV+n+ADyNddKtQqM0BQFnSoVcLRHArDcVaePUmITLUbzIl5hx3DWmW93SyNSYU3soB/3crag8=,iv:/DrtZD1LVT4IiGDSG3T64RrIto+gJUt+E9X6IERHXwc=,tag:EnDWPP8PqRGFtwxDm74Pmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
