apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-prometheus
    namespace: monitoring
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:qoDUKjj6lE9X5q5wU2qnULPfL0lG0fS5fQKbxfdbguXHHhuC,iv:G5DK/jTbxT8Vy96/qoMFnuG+RHtU1BBYQgu12fWqGdk=,tag:EkpdrPt+M0MePRWrwzsgaw==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:96ohX5VkQT8ON+YgKIDtnD6iNp+nwAk5ZY2z/nKgOcY=,iv:BGf5irzoHOfQS6tJ7P9Bal6ukGx17LeiEoJi9XFde3A=,tag:JjF190b/RGUY/kf62q61ww==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:h4vKaOqhgbxbBZYD2vw0A70Lk8DdPqZIo404uRKX3GvPQHFkFkaOCeI7jU8=,iv:r5xhtQ/BBjYT47msk6Rqk7gsUqRRucID4a+rQjNqExA=,tag:LI7QGISB2xj2hfJvpBaeag==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bDRyOGJ5WHE4bEdrNE1D
            SXJObWc2V2Vlb3dLajUzOTY2bFJPTTVRdUd3CmxibXhyc3BINU1TUnVFb3AwTnJH
            ems5QXU4em9WcUZKZUsrN0dDbTZlZWcKLS0tIFJCT0h1UkhnTUU4NTBjeEpHTjVW
            U08ybHpVOHFZdWRoaFhERkVNblRuNDAK9naAU/P5NiSWd5iF3lh/psBe3ULrOedj
            e7odik57AbsfXrswLvO5zYmZ+fhclIV6CDDnEkRvw4WCX7esh57ihw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T17:28:27Z"
    mac: ENC[AES256_GCM,data:s9aIeK7L+yBxQgvugwy9PbbSp6bE1HvhpwEGjc8yTNTamg0QoHlvTfURXzVMPMdFzHST4iGd7YrjZaZguxFujSjrKSTNhhkcd9l3fbJzw+GjtewcHsoimddwDz911zA7vjWNjS3t12Z4cb5Vsg7eJwQQaKXkaOVRxrEUu+J3JrE=,iv:8Wk35Z1GSMFxsvRD20Blve4tCpjp1bQcH+/A7NLfbCA=,tag:kHZgTGGDUUxF1nZUrzfuKg==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
