---
apiVersion: v1
kind: ConfigMap
metadata:
  name: necesse-cm
  namespace: necesse
data:
  WORLD: "Fabler"
  SLOTS: "10"
  OWNER: "Echo"
  MOTD: "Fabler"
  PAUSE: "1"
  GIVE_CLIENTS_POWER: "1"
  LOGGING: "1"
  ZIP: "1"
  WORKSHOP_COLLECTION: "3797557934"
  WORKSHOP_IDS: ""
  JVMARGS: "-XX:MaxRAMPercentage=75.0"
