apiVersion: v1
data:
    serverPassword: ENC[AES256_GCM,data:fIuF1Mo1xfSATQQg,iv:FX96EpCxPIGoRiyiX3YW6u6+7v9Sflww/IRiElKIRVs=,tag:kASzI0bRAVx9W6Rye4CKdA==,type:str]
kind: Secret
metadata:
    name: necesse-secrets
    namespace: necesse
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOEhNaHI2QzZqcTAyT1px
            bHVPU2ZQK2VxQXpMSXpUZUZCNTNNZXlqL25FCkRNeVFOTEJyYmNQM3Z5Q3VhdVFN
            SHlyc2dCQm1ZMWY3RzJZbFlDYUFsTmcKLS0tIGNybER6SGJPUzc2d0kvV21LTG1Y
            WkJuZ2dxTFgzVmxVVjJaajNGTk1NMVUK31LgWKj1tpmiT2Er9+6CrqBaZdc7qJCl
            lR4/sjH3BYP8i/t3SynC3NBpgMZZAznjMgMpOXiCjmjZs9Cs1Oivog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
    encrypted_regex: ^(data|stringData|secure)$
    lastmodified: "2026-09-07T16:22:19Z"
    mac: ENC[AES256_GCM,data:8evs4tB8z13teR95ChFu2jHMbdB6jpzZTDGAvUxXYZtg91N3xDI0cHaiKFV+ZOtWKLZYDyjptzOBbMvLJ951AfAuuw1axcpHURj7+XuEdgT8Vrc4qiTpfR3vXjrBhqVcUGVzKKCQG7Q0/ZsTWxwTOjCYuvpSJYw/HCA4ga1Jhf8=,iv:XzQG2PbruOEI6XuDGkgJPyPg66upyi76BrPibi8ONYo=,tag:PQMVCH0oc8S8F/1VWUM2Fw==,type:str]
    version: 3.13.3
