---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: necesse
  name: necesse
  namespace: necesse
spec:
  type: NodePort
  ports:
    - name: game
      port: 14159
      protocol: UDP
      targetPort: 14159
      nodePort: 30159
  selector:
    app: necesse
