---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - soulmask.yaml
  - minecraft.yaml
  - vrising.yaml
  - core-keeper.yaml
  - foundry.yaml
  - enshrouded.yaml
  - palworld.yaml
  - satisfactory.yaml
  - valheim.yaml
  - metrics.yaml
