controller:
  replicaCount: 1
  priorityClassName: "system-node-critical"
  hcloudToken:
    existingSecret:
      name: hcloud
      key: token

node:
  priorityClassName: "system-node-critical"
  hostNetwork: true

storageClasses:
  - name: hcloud-volumes
    isDefault: true
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
