---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# hcloud-secret is created by Tofu via the flux-bootstrap module's
# managed_resources (network ID is only known after server is provisioned).
resources:
  - ../base
  - helm-repos.yaml
  - monitoring-namespace.yaml
