apiVersion: v1
kind: Secret
metadata:
    name: capacity-watch
    namespace: capacity-watch
type: Opaque
stringData:
    HCLOUD_TOKEN: ENC[AES256_GCM,data:gUZDYmhIMTXLVJYRKoRIjp7ooKgur57zwQBA+JGlWiW0B5rEYG1J/Or+dTJ1EvXmqRzGZk8czCVL6HgASP7a6g==,iv:CumDhHSPPM+Hzk9cg7yRDgf34hNmQTiXcyXydfk1ygY=,tag:4/WwEXcBRjrKvauN2/ztbQ==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:RiRFhXSXVY5SposCmd3seMkupYXaks/IFMetPooKrCvThIhnWs3uwZOnY011TjT+/4oFD8Jz/kfVbAzDYtVnRdwh8EE1kENlqOFNB7KzakA/hY5NSfG5ENq1XqNn,iv:Y8M0CL0FD25AFJ1CIixTWQX7ob2HC38bhs0RgiU/fy0=,tag:f9IxbiESzjFrwnHDwjrsnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WVFybFNqTXFYaDFLUzZ3
            Y2c3S2F2dGd6Qk4rcjBBQWFRSjJ5Ty9JYVNzCktxTHJvYjcxWEphNjN2Z3prRmdC
            Y2VOaXRueW5KMDlpWDZ2bGVRV3lobk0KLS0tIG9SakJkbEd3RWlHbXVRWWN6VU94
            Y3dZTldhd2x1WXBVcVQ4TTVXZnNYSzAKs1NV2NCKRZrwX2juYyzFpAvH4/p0+b5c
            U5rrJlphRKc58EnNUke/QRLwyhlrs2pwpBUszVPsRczsUNXPyO2Vcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
    encrypted_regex: ^(data|stringData|secure)$
    lastmodified: "2026-10-04T13:38:14Z"
    mac: ENC[AES256_GCM,data:LYscof05W6sYYDImQDq15nVExnmS6iIh+bHYtY4XWEtzG5aYJz1CR6WIsqjQCwyfzl7pWMdWGxZ3btPGh3kOgcyUlOPi8JSPF6GUPgELZWSm5mvE7C0B2JMQH7BjL5HP0/BCHuXHEVesc1y2jvqjzOl1O9xy8WLBUTc4mgg0neE=,iv:bBbGmIuHfRAokzxFf3fcFYFwhNLpR+aEh388B21bjvs=,tag:WbSrUnV5q29Jhc3wOB9gpg==,type:str]
    version: 3.13.3
