---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: valheim
  name: valheim
  namespace: valheim
spec:
  type: NodePort
  ports:
    - name: gameport
      port: 2456
      protocol: UDP
      targetPort: 2456
      nodePort: 30456
    - name: queryport
      port: 2457
      protocol: UDP
      targetPort: 2457
      nodePort: 30457
    - name: queryport-2
      port: 2458
      protocol: UDP
      targetPort: 2458
      nodePort: 30458
  selector:
    app: valheim