apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:az0Fyw0DC5A7Uo0W5AYCLF1Gor2Cu9IcgoFP6UZQjAS1rAnZak2LNt7Y3cw=,iv:Yos/S/SsDFx2PCHTB49Fb9dIcSDx7EtFkZugUPwR8JQ=,tag:VGvGejZmiV7QpJt7zEaaTg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:Vy2yRSYhT4dMORHrrBK8SFhDYDhL2kpgbjVfKOis0Lfn2QB8qXGV1pHr5xmx8liHo7+ojetCA03EaERiKDrukGOVUI92F3WrmLIUv+PVz1g7LuUgT/F4HQ==,iv:rOLXqIr5SVSat+4/A1wQxIIRWnknrcPzcvwvzT+NmbE=,tag:ev5xuh1iM8A+/5XPnTy4aA==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: shared-secrets
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: booklore,identity,minecraft,vrising,core-keeper,foundry,soulmask
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: booklore,identity,minecraft,vrising,core-keeper,foundry,soulmask
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSjZGT0R0SGRmZ2Z1RDZx
            TlltVjBTNWtrWGl3MjE3RkdyKzJXUzdXYVNNCmRJRFhtT0tuaTBxQ0xxWkRsZXY2
            NUFkVmlXT3o3aXYxWno4T1FCVVprNzAKLS0tIE9wS1NEc25qNWxjWDlQUEJ1VXlF
            RVJ4NU1LaHhTY3VpbnZaL2pLenIwNXMKbzjsntBi3inpW3kdrZvfqQAFktD1zEIr
            UyAcTvSCsOhZYc170zMJAQFRlZqSfjtxf+on97NPQL9o+v4LgSOWrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T13:28:45Z"
    mac: ENC[AES256_GCM,data:/ZxxQzW4CPePg+gM4LFS3Kebwv/t9C8KdUISSrcJIatSpwTwzgr6V70uoifQXDv2/JiaFR+gdKZgCVBKhTgTi+C5wlEkBxza/fQkwlDQ1nXBkNYKp/1Ul2RpOoVNFjRnBu4fjAowpYkD1cpMF4jkl7a30YnOO9n17sWbX5NVc2M=,iv:xDfsDiOYQhpN7GzAdJAG61TCpst6JihnvRc7f72ap9E=,tag:7wI7z8y20+P4P4RMiHJAqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
