apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:7afaV6MWRrvWpR+A7scMbL5EFbkDINtTv52SPGNyuLoYabihfJrs+Xb1amU=,iv:t3LkyqlToURcAdkcmb4oHsJFlpBORUZ9Ag1nsmtpNYY=,tag:JtcHNw9+rMaCiCiPkB0xdQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:fxVNTmeZ6Yl/CHZyjz+yQozyHrK16xnsDrfbIMn/zrklizpwWcHQRxVJYqF7pE0mc27qD9rzHGUb9MVkDWMO0QWs6ELdKUxChhXwQTjowphBcjVw3/+7hA==,iv:Okadx7GTkrTJPLkHq2Pk8qOsbdHuAGXrRx5XsSAlMv8=,tag:azCoHElGs87ZWEUhh8NNrg==,type:str]
kind: Secret
metadata:
    name: r2-credentials
    namespace: shared-secrets
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: booklore,identity,minecraft,vrising,core-keeper,foundry,soulmask,paperless
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: booklore,identity,minecraft,vrising,core-keeper,foundry,soulmask,paperless
type: Opaque
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMUJZbWpUajcxZXFHSnpE
            akxmVWJGZnh0VkgvalAyNVBFSzRJUWFmVUdjCndlRzRabjlQM1VjYUhDWkl2OWFI
            bFhwL3FOVkVQZUNUZThPMzVtWVMxdlUKLS0tIGFTbWFuY1dZc2JCYllKOXhldmtj
            MUZTdUVwVlRzcmVVSEhTRFJOdFZwRjAKWc0CmaJbtSUKrSpALraFZypVgvd1b4Sq
            WWYN5B/UxkQa0DF22zQ6I1tXA8hZYwwHtAeo6CvdjswN3ZA0dYEASg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T00:55:12Z"
    mac: ENC[AES256_GCM,data:hdQZ990sZAHPgRkQj7pAosO3rfMor6H9dtse49TDyJibDkIjGMLdhL2GVY5AqKydgQAmnSG7uzk8ro3UypiT9ykwkcLgpk/kWfr9lSaMBHq9xlVVINsC/eZGiKOLu7+gOPAg9C9qa4/Xwh6ubrIqIG2gxnk2xOXaCwkWWFome6s=,iv:ZtXPtvKemGGHrXk+qWwtmwAhQMXLNT6PuUU0Djm8cUY=,tag:CM9CzV9xW/V5DrUiFWh4/Q==,type:str]
    encrypted_regex: ^(data|stringData|secure)$
    version: 3.12.2
