apiVersion: v1
kind: Secret
metadata:
    name: telegram-credentials
    namespace: shared-secrets
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring,uptime
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring,uptime
type: Opaque
data:
    bot_token: ENC[AES256_GCM,data:LODjI4uWgIRdd79TBSTS4zZpwQq0oxsCRKSyThZBIGrr12TV40/9e9rx/ApI1+zQBEO74AKCRhGlWqorqBvCFw==,iv:CZlPr7qYpuJn1hYHFG/O5C4gSZghRbmK5FF9RFOWYfA=,tag:NbiTNd2BJxz077iEYds4Hg==,type:str]
    chat_id: ENC[AES256_GCM,data:AWEyhMiVxPM+8gF5,iv:8JyGUWxNsS+VfVstP0GhpQW7zKc4jpu+ieJ/xLfDQ18=,tag:iOSTnjJMCYNN0Xg1osjMeA==,type:str]
sops:
    age:
        - recipient: age14a000yfg3226nakz8gycgtw4c7zugyply4jv29p6fmuy8ak05cqsu5cdx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSWNiSGQ0SEpqREhXSkJ6
            alp0MEFrTGV3cmNORFNaaUVmM3Q5djdVdzNFCmljWnlWbjdkWVUyUDZNLzAzNERS
            Z2xzYkdySThPUlpWLzhPNTFBVFg3SnMKLS0tIFRRbmxob3ZDbjN5dkswWW55azlS
            Q1RXNmpWSUhkTGZzUWYyOHJybVByaTQKXU0bwTaUqi2NSQ+pQDVyHs4lVx7ybxw+
            vojwDLiuBf4nyjEq7EGrkVdInCOuhMghCeM78COQxZkfPtxYv69siQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T16:37:58Z"
    mac: ENC[AES256_GCM,data:wSy+He9pO2qx6NPAY6LohVg45B0l4p3wMAc2R/Vo6hmOqh1WHtnZhXSiAySAr+z/rFPfbyUsCj33skkYm7uEthhFHa5loKfSAb393B83chfFvTNysBivNF5ckfOodeNUq2CwH4oInGNX8ekv7aPIxvEr25EguChvnz0RogR9zZA=,iv:ZI6i4FIFjHQq8/ebL2j7hsT6DH3t0NCjyzOTxyoHc0U=,tag:63+HxuKUeN48UmT7WEniIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
